### ISSUE TITLE
Duplicate Commissions on Export

### ISSUE THREAD

**Issue by carter2422** [easydigitaldownloads/EDD-Commissions#100]
In v3.2.3 I just got duplicate commission earnings exports for each user. 

All amounts are equal, so each row was simply added twice on the batch export using the normal **Generate Payout File** with a date range.

**Comment by ghost1227** [comment]
@easydigitaldownloads/core-devs I haven't been able to reproduce this. Could this have already been resolved? Can anyone else reproduce it?

**Comment by ghost1227** [comment]
However... I have managed to make it fail to export consistently... As of now, it's timing out for me semi-frequently.

**Comment by pippinsplugins** [comment]
I've never seen this happen on any of our sites or from any other customers. I vote we close as invalid.
