### ISSUE TITLE
REST API Querying Slow

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/EDD-Commissions#104]
When using the REST API to query `commissions`, the request speed is over 5s. In comparison to this, the `stats` and `sales` endpoints both have request speeds of 0.1s.

The request speeds are taken when using the REST API on the EDD site.

**Comment by pippinsplugins** [comment]
I'm going to start digging into this (and related items) once EDD 2.5 and EDD Recurring 2.4 are out.

**Comment by ghost1227** [comment]
@sunnyratilal I did a comparison between the `commissions` query and the queries available in core and don't really see a reason that the `commissions` query would be inherently slower than any other query. Additionally, my tests haven't shown a differential of nearly what you saw when you opened this issue. That said, this _is_ a year and a half old issue, it's possible that changes elsewhere in the extension have negated the original issue (or at least alleviated it). Regardless, it seems to me that this is a great candidate for the new `EDD_Commission` class... thoughts? Once you're done that class, at the very least I'd anticipate it being the most optimal way to retrieve the necessary data.

**Comment by sunnyratilal** [comment]
This task is a bigger one that initially seems.  @pippinsplugins, we've had numerous discussions in the past about with alongside @cklosowski when I was building the iOS app.

The slowness here is to do with the way we are storing the commissions data. It's stored in an array in `post_meta` which makes querying it painful. There's no real way around making this faster without database schema changes or a move to a custom tables.

Last time I mentioned this (back in July 2016), @pippinsplugins I do remember you saying that you wanted to move to custom tables.

**Comment by ghost1227** [comment]
@pippinsplugins If that's accurate, I don't see us completing this during the 3.3 release cycle. A database redesign is a bit bigger than we probably want to tackle in the next four days.

**Comment by pippinsplugins** [comment]
Let's go ahead and close this as wontfix and then address it through the move to custom tables.
