### ISSUE TITLE
Commissions set to 0 will use next commission value in list

### ISSUE THREAD

**Issue by carter2422** [easydigitaldownloads/EDD-Commissions#105]
If a product has multiple users receiving commissions, and the first one is set to `0` percent, then that first user will receive a commission in the value of the second user, rather than the specific 0. 

For example, here's a $3.00 product with two users, the first of which should not receive anything (per their preference): 
![screen shot 2016-01-04 at 2 36 38 pm](https://cloud.githubusercontent.com/assets/1648631/12099833/a6e00868-b2f0-11e5-932d-8ced34a1a28a.png)

When the product is purchased it records commissions for *both* users at the second user's rate:
![screen shot 2016-01-04 at 2 37 28 pm](https://cloud.githubusercontent.com/assets/1648631/12099890/03e90230-b2f1-11e5-80e2-62adfab3452a.png)

**Comment by cklosowski** [comment]
Thanks. Will get it into the next release.
