### ISSUE TITLE
Commissions list table pulls incorrect rate if download commission type is changed

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#110]
To replicate, create a download with a percentage commission and make a sale. My example was `70%` commission.

Make a sale and in commissions you'll see a Rate of `70%`.

Change the download to be a flat rate, and change the value to `7` for a `$7` commissions payout, and make a sale, and your new commission will show a rate of `$7` (correct), but the previous commission will show `$70`. The data will still be correct in that it was only a `$7` commission, but the rate is pulling from the download not the commission entry.

![screen shot 2016-01-08 at 9 32 21 am](https://cloud.githubusercontent.com/assets/1390124/12201628/0b1376ba-b5eb-11e5-9721-969c734eb1b3.png)
![screen shot 2016-01-08 at 9 32 14 am](https://cloud.githubusercontent.com/assets/1390124/12201632/0fa8b2e4-b5eb-11e5-8fd8-fe2f3196ec16.png)

**Comment by cklosowski** [comment]
Currently we don't store the commission type when it's recorded, so we can't do this yet. Going to punt for later on when we re-write this. The data/payouts is fine, it's just a visual that's incorrect.

**Comment by ghost1227** [comment]
@cklosowski Not sure if I'm on the right track, particularly given that I can't think of a way to make this 100% accurate retroactively, but I _think_ this works the way you intended.

**Comment by pippinsplugins** [comment]
@ghost1227 PR looks like it is on the right track. Will test shortly to confirm.

**Comment by pippinsplugins** [comment]
Works great. Merged.

**Comment by ghost1227** [comment]
@pippinsplugins so we're not going to worry about retroactive effect?

**Comment by pippinsplugins** [comment]
Nope.
