### ISSUE TITLE
EDD Recurring 2.4: Allow commissions to be recorded on renewals

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#113]
This is a compatibility issue for EDD Recurring 2.4, which will allow store owners to record commissions with renewal payments.

**Comment by cklosowski** [comment]
Not tested yet, but UX is in place and helper functions in place.

**Comment by cklosowski** [comment]
Will be testing this first thing next week, or over the weekend if I get a chance.

**Comment by pippinsplugins** [comment]
Is this different from #102?

**Comment by cklosowski** [comment]
Nope Same thing, I think we must have missed #102 when we were making the list of 2.4 issues we needed to do.

**Comment by cklosowski** [comment]
Ok @easydigitaldownloads/core-devs this is ready for testing. I've gone through and made sure things were working. Just need some extra eyes to see if I missed anything.

**Comment by cklosowski** [comment]
Things to test:
1) That the overall setting is respected (Downloads>Settings>Extensions>Commissions).
2) When 1 is enabled, that the download specific setting is respected (In Commissions Settings of download metabox)
3) That all the hiding/showing is correct

**Comment by pippinsplugins** [comment]
@cklosowski looks really good. A few small changes requested on the PR>

**Comment by mintplugins** [comment]
For this, we need to set up a commission on a recurring product and check renewal payments to see if commissions are generated, correct?

**Comment by cklosowski** [comment]
@mintplugins Yep, Create a subscription, and go into the subscription details in admin and start manually creating renewal payments (that's how I tested).

But like I said above, there is a global setting to allow recording recurring commissions, so we need to be sure that is respected on both false and true. As well as a product specific level ability to disable the recurring commissions, even if the store has it enabled (because you know that'd be the first feature request as soon as it went live :P )

**Comment by cklosowski** [comment]
@pippinsplugins fixed the isseus on the PR.

**Comment by SDavisMedia** [comment]
@cklosowski Everything looking solid for me on `issue/113`. Global setting works. Single product settings override global just fine and can be changed from one renewal payment to the next. All showing/hiding is on point. :+1:

**Comment by pippinsplugins** [comment]
Let's merge!
