### ISSUE TITLE
Bulk processing marks all commissions as paid in a single loop

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#114]
Our bulk processing tool is fantastic for calculating the amounts that need paid out . . . but it's not good at marking those commissions as `paid`. Turns out that every commission record that is included in the payout gets marked as `paid` in a single loop:
```php
/**
 * Print the CSV rows for the current step
 *
 * @access public
 * @since 3.2
 * @return string|false
 */
public function print_csv_rows() {

	$data = $this->get_data();
	if ( ! empty( $data ) ) {
		return $this->stash_temp_data( $data );
	} else {
		$this->get_temp_file();
		$temp_data = @file_get_contents( $this->temp_file );
		$data      = json_decode( $temp_data );
		$row_data  = '';

		if( $data ) {

			// Output each row
			foreach ( $data as $row ) {

				if ( ! empty( $this->minimum ) && $this->minimum > $row->amount ) {
					continue;
				}

				$i = 1;
				foreach ( $row as $col_id => $column ) {

					if ( 'ids' === $col_id ) {
						continue;
					}

					switch( $col_id ) {
						case 'amount':
							$column = edd_format_amount( $column, 2 );
							break;
					}

					$row_data .= '"' . addslashes( $column ) . '"';
					$row_data .= $i == 3 ? '' : ',';
					$i++;
				}
				$row_data .= "\r\n";

				foreach ( $row->ids as $id ) {
					eddc_set_commission_status( $id, 'paid' );
				}

			}

			$this->stash_step_data( $row_data );
			@unlink( $this->temp_file );
			return false;

		}
	}

	return false;
}
```

The `print_csv_rows()` method runs after all of the bulk processing is completed and runs in a single step.

This is the item causing EDD commission payouts to fail on the EDD commission site.

**Comment by pippinsplugins** [comment]
@cklosowski Could you mark this down on your todo for two weeks from now? We need it done before our next EDD payout.

**Comment by cklosowski** [comment]
@pippinsplugins i'll try and get this done this week.

**Comment by pippinsplugins** [comment]
Thank! We just need it before the 15th of February :)

**Comment by pippinsplugins** [comment]
@cklosowski Looks like it works really well. I'll need to test on a site with thousands of records to be sure though.

One thing: could we reload the page after marking as paid? That way the user can see the change from unpaid to paid.

**Comment by pippinsplugins** [comment]
When we get to this stage, let's show a break down of the commissions that will be paid. That way the site admin can review the commissions before downloading the file.
![screen shot 2016-02-11 at 4 01 43 pm](https://cloud.githubusercontent.com/assets/1034109/12992248/d48fbfbe-d0d8-11e5-8718-e54fb049cbba.png)

**Comment by pippinsplugins** [comment]
Testing it now with 1300 commission records.

**Comment by carter2422** [comment]
@pippinsplugins is this something that might later enable generating a payout report *without* marking them as paid yet?

**Comment by pippinsplugins** [comment]
@carter2422 Yes. After the "Download Payout File" is clicked, it shows a `Mark as Paid` button:
![screen shot 2016-02-11 at 4 10 54 pm](https://cloud.githubusercontent.com/assets/1034109/12992431/0d320d44-d0da-11e5-953b-52b41eeffee1.png)

If you don't want to mark them as paid, just don't click the button.

**Comment by pippinsplugins** [comment]
Definitely need the redirect, otherwise there is the possibility the user could try to mark as paid a second time:
![screen shot 2016-02-11 at 4 17 33 pm](https://cloud.githubusercontent.com/assets/1034109/12992611/05201d34-d0db-11e5-8345-872e939cc91d.png)

**Comment by pippinsplugins** [comment]
Worked perfectly though, @cklosowski, nice work! Just a bit of polish needed then we're good to go :)

**Comment by carter2422** [comment]
But what if I want to click *the button*....

That's excellent and exactly what I've been wanting :)

**Comment by pippinsplugins** [comment]
NO CLICKING THE BUTTON!

**Comment by cklosowski** [comment]
They can try and mark as paid again it won't work. When the batch is done the option with all the Ids is deleted. So it won't mark anything as paid. We can just hide the button or something so it's clear its over.

**Comment by cklosowski** [comment]
I'll try and work a redirect I to the batch processing. I don't know if we left ourselves an out for that.

**Comment by pippinsplugins** [comment]
Seems like a redirect via javascript would be trivial.

**Comment by cklosowski** [comment]
@pippinsplugins we need our core batch processor to accept a redirect, right now it's messages, downloads, or errors. I'll work on something though.
