### ISSUE TITLE
Ability to export commissions by status

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Commissions#115]
Customer requested, and I quote:

> The ability to export “Unpaid”, “Revoked” and “Paid” would be very useful for reporting and record keeping purposes (basically a full report for any given date range). At present the only export functionality is “Generate Payout File” which isn’t useful for record keeping purposes."

**Comment by pippinsplugins** [comment]
:+1:

Nice and easy to do now too with our bulk export options.

**Comment by cklosowski** [comment]
Ok this is ready for some testing. It's added a 'Type' dropdown and then a status dropdown.

If you choose 'Overview', it uses the current export with gives all the statuses by month.

If you choose the 'Detailed' option, the 'Status' dropdown is enabled, allowing the export of commission records by status for the months. This is pretty much a dump of the data:
![screen shot 2017-06-20 at 10 01 38 pm](https://user-images.githubusercontent.com/1390124/27367910-40ac93f0-5604-11e7-95d4-5a3844309442.png)

![screen shot 2017-06-20 at 10 01 44 pm](https://user-images.githubusercontent.com/1390124/27367914-462f9570-5604-11e7-8503-b68a4ca0f4d6.png)

![image](https://user-images.githubusercontent.com/1390124/27367923-50a0c682-5604-11e7-92fd-1e18f109b2bd.png)

**Comment by cklosowski** [comment]
@davidsherlock Since you mentioned you were the one asking for this, thought I'd ping you on it so you're aware of it's progress.

**Comment by davidsherlock** [comment]
This is awesome @cklosowski, big thanks for adding this!

I have a few suggestions however:

- The download ID is accompanied with the download name, I feel the same should apply to the User ID so you can quickly see the username of the vendor without looking up IDs. I believe the commissions grid in the admin panel displays the display name, maybe the report should display the username `username (display_name)` for maximum readability?

- It would be useful to have the original item cart (sale) price in the table so we know the base amount the commission was calculated from. I created a function for my invoice plugin to calculate fees, could this be added to the report?

**Comment by davidsherlock** [comment]
For reference, here is my _messy_ function :)

```
public function get_service_fee($commission, $total) {
            $payment = new EDD_Payment( get_post_meta($commission->ID, '_edd_commission_payment_id', true));
            // var_dump($payment);
            $variation           = '';
            $download_id = get_post_meta($commission->ID, '_download_id', true);
    				$has_variable_prices = edd_has_variable_prices( $download_id );
    				if ( $has_variable_prices ) {
    					$variation = get_post_meta( $commission->ID, '_edd_commission_download_variation', true );
    				}
				$serviceFee = 0;
        $cart_items = $payment->cart_details;
				foreach ( $cart_items as $key => $cart_item ) {
          $item_id    = isset( $cart_item['id']    )                                  ? $cart_item['id']                                 : $cart_item;
          $price_id   = isset( $cart_item['item_number']['options']['price_id'] )     ? $cart_item['item_number']['options']['price_id'] : null;
          $cart_variation = null;
          if ( isset( $cart_items[ $key ]['item_number'] ) && isset( $cart_items[ $key ]['item_number']['options'] ) ) {
            $price_options = $cart_items[ $key ]['item_number']['options'];
            if ( edd_has_variable_prices( $item_id ) && isset( $price_id ) ) {

              $cart_variation = edd_get_price_option_name( $item_id, $price_id, $payment->ID );
              if($cart_variation == $variation)
              {
                $serviceFee += $cart_item['price'] - $total - $cart_item['tax'];
              }
            }
            else
            {
              if ((int)$cart_item['id'] == (int)$download_id) {
    						//$serviceFee += $cart_item['price'] - $total;
                $serviceFee += $cart_item['price'] - $total - $cart_item['tax'];
                break;
    					}
            }
          }
				}
                return $serviceFee;
        }
```

**Comment by cklosowski** [comment]
I think adding the username might be a helpful addition. I'm not sure that adding the cart item value makes sense here. This is a commission report, not a report of an item on a payment. The Payment ID is provided so that information can be looked up at the will of the exporter.

I just think the context of 'commision' export and then a single column about 'item price' seems a bit off in this instance for a couple of reasons:
1) Since Item prices can change, and people do odd customizations, it's possible to get an inaccurate number here, instead of simply looking up the item.
2) If a user needs a custom detailed report with custom columns, the batch processing api for exporters is fully open. (I'll add a couple hooks into the dropdowns that allow for defining another option for exporting so it can be customized.

**Comment by cklosowski** [comment]
Ok a filter has been added to allow developers to add a customized export class using our batch exporter:
```
$options = apply_filters( 'eddc_export_classes', array(
	'EDD_Batch_Commissions_Report_Export'         => __( 'Overview', 'eddc' ),
	'EDD_Batch_Commissions_Report_Details_Export' => __( 'Detailed', 'eddc' ),
) );
```

**Comment by pippinsplugins** [comment]
@cklosowski this looks and works great. Only thing I'd like is a tool tip next to `Generate CSV` that explains what differs between the `Detailed` and `Overview` options.

**Comment by cklosowski** [comment]
Tooltip added @pippinsplugins

**Comment by pippinsplugins** [comment]
Looks great, merged.
