### ISSUE TITLE
Calling eddc_get_recipient_rate() with its default parameter values throws a notice

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#116]
When you call eddc_get_recipient_rate and do not specify any of the values for the parameters, or use 0 for the download ID and set the user_id to the one you want (to get a user's commission default rate), a fatal error is thrown since without defining $download_id, $rate is never defined before it's attempted to be cast to a float.

**Comment by chriscct7** [comment]
This was caused by https://github.com/easydigitaldownloads/EDD-Commissions/commit/af78a70304a1d7fa34a28e6bad943ffa7300aa8d

**Comment by chriscct7** [comment]
Example calls that error:
$rate = eddc_get_recipient_rate();
$rate = eddc_get_recipient_rate( 0, $user_id);

**Comment by pippinsplugins** [comment]
@cklosowski Could you look at this tomorrow please? I believe we have at least two open support tickets that this resolves.

**Comment by pippinsplugins** [comment]
To be clear, this is not a fatal error, it's just a PHP notice that FES reports (I think poorly) as a fatal error to the user:

Undefined variable: rate in /MAMP/edd/wp-content/plugins/EDD-Commissions/includes/commission-functions.php on line 266

**Comment by cklosowski** [comment]
I only get the notice when no `download_id` is provided, we cast `0` automatically for the user ID, so even if you don't supply it, we have a value to 'test' against.

**Comment by cklosowski** [comment]
I'll go ahead and define `$rate = 0` before any logic happens and also save us a DB call to the usermeta by wrapping the `$rate = get_user_meta( $user_id, 'eddc_user_rate', true );` call to only run if the `$user_id` isn't empty.

**Comment by cklosowski** [comment]
@pippinsplugins @chriscct7 PR is ready for your review.
