### ISSUE TITLE
In Gateway Settings, hide Default Gateway chooser when only one gateway active

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/EDD-Commissions#129]
When there's only one Gateway enabled, it should be the "default" by default, and then we can hide some UI and make the whole thing simpler.
![selection_226](https://cloud.githubusercontent.com/assets/341412/13960878/75f2e072-f030-11e5-9485-92abed6248e3.png)

**Comment by michaelbeil** [comment]
Would we also want to hide any settings for individual gateways below the Gateway Settings section since only one gateway is enabled?

**Comment by pippinsplugins** [comment]
@topher1kenobe wrong repo.
