### ISSUE TITLE
Introduce EDD_Commission object

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#133]
Just like EDD_Customer, EDD_Payment, and EDD_Download, we should introduce an EDD_Commission object that acts as an abstraction layer for commission records.

Doing so will make the transition to custom database tables significantly easier.

**Comment by sunnyratilal** [comment]
Progress update: there are issues with the meta saving. Once I've fixed that, this is ready to go.

**Comment by sunnyratilal** [comment]
Ready for testing.

**Comment by cklosowski** [comment]
Going to get some tests setup for this today.

**Comment by cklosowski** [comment]
Looks like we need to get 'type' into the class since #110 was introduced that stores the type.

**Comment by cklosowski** [comment]
Turns out you cannot use static fixtures with WordPress 4.3, so we'll have to ditch support for that version to move foward.

**Comment by cklosowski** [comment]
Ok @sunnyratilal I've added some unit tests and fixed it up to be a much faster test suite by doing the setup of tests on the class, not each individual test, so things move quicker.

**Comment by sunnyratilal** [comment]
Tests look fantastic @cklosowski!

**Comment by ghost1227** [comment]
@cklosowski @sunnyratilal This looks good to me!
