### ISSUE TITLE
Replace all instances of get_post_meta() for payments with edd_get_payment_meta()

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#135]
There are a few places where get_post_meta() is still used for retrieving payment meta data. These should all be replaced with edd_get_payment_meta() to aide in the gradual process of moving to custom tables.

**Comment by ghost1227** [comment]
@pippinsplugins I'm hesitant to attempt anything here. I've gone through all 69 instances of `get_post_meta` in Commissions currently and I'm honestly not positive which of the remaining instances have been replaced with `edd_get_payment_meta`.

**Comment by cklosowski** [comment]
Looks like there is only `1` instance of using `get_post_meta` for getting payment meta, and it's in the list table. The rest are all downloads or commissions:
![screen shot 2017-02-07 at 4 53 16 pm](https://cloud.githubusercontent.com/assets/1390124/22717032/fd82a720-ed55-11e6-8c89-506c98e76406.png)

![screen shot 2017-02-07 at 4 53 27 pm](https://cloud.githubusercontent.com/assets/1390124/22717038/0176161e-ed56-11e6-848c-6630ca8ff3d9.png)

the `INVALID` one is the one that I found that was for the payment meta, and I changed it so it's not listed anymore.

**Comment by cklosowski** [comment]
Forget me...that one I changed isn't correct. It was a payment ID, but was getting the commission payment Id...I don't see any references to getting payment meta using `get_post_meta`

**Comment by ghost1227** [comment]
Ok, so I wasn't losing my mind. I read through every one twice, but none seemed to be relevant to payment meta.

**Comment by ghost1227** [comment]
@pippinsplugins Can this be closed?

**Comment by pippinsplugins** [comment]
Yep, looks like we're good here.
