### ISSUE TITLE
Payout file CSV columns: where's the ID?

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Commissions#138]
I'm a little confused by this. A customer requested that the user ID be included in the future as a column in the payout CSV file. I did some quick tests and looked at the code to re-familiarize myself with the feature. However, something isn't clear to me.

I see:

```
$current_data[ $key ] = array(
    'email'    => $entry['email'],
    'amount'   => $entry['amount'],
    'currency' => $entry['currency'],
    'ids'      => $entry['ids'],
);
```

in there but only the first three keys show up in the CSV as columns. Is 'ids' supposed to be a column in the CSV file?

**Comment by pippinsplugins** [comment]
`ID` cannot be included because it would make the file invalid for PayPal.

The `ids` are used for the batch processing API so that it knows more easily which rows belong to which users.

**Comment by brashrebel** [comment]
That makes sense. A customer told me that PayPal allowed for one additional, arbitrary field of data and they thought it would be useful to include the vendor ID for record keeping. I can tell them it isn't possible if that's the case.

**Comment by pippinsplugins** [comment]
Ah, I could be wrong then. Let's check into it. If PayPal permits it, let's do it.

**Comment by brashrebel** [comment]
Turns out PayPal does support a 'Custom Note' field and an 'Customer ID' field: https://developer.paypal.com/docs/classic/mass-pay/integration-guide/MassPayUsingUI/#payment-file-contents

We're not using either of those in the export file. A customer has requested including the vendor ID for record keeping. Should we support either or both of these fields? If so, what data should they contain by default? Maybe we could include at least a hook for populating those fields when someone actually does need them.

**Comment by pippinsplugins** [comment]
PR submitted that adds the user ID to each row.

**Comment by SDavisMedia** [comment]
It's working well for me. :+1: 

<img width="276" alt="screenshot 2016-11-03 14 02 41" src="https://cloud.githubusercontent.com/assets/2359131/19985075/347ff97c-a1ce-11e6-817d-7e36c2ecc3ad.png">
