### ISSUE TITLE
Incorrect amount being sent to PayPal (adaptive payments) when set to instant payout

### ISSUE THREAD

**Issue by benjaminprojas** [easydigitaldownloads/EDD-Commissions#142]
### Issue:

When sending attempting to instantly payout commissions using PayPal Adaptive Payments the amount being sent to PayPal is the total for the vendor, not the entire total.  For example, 

Download: $10

Commission User: 2

Commission Rate: 80

Price in PayPal: $8.

![image](https://cloud.githubusercontent.com/assets/962530/18146873/073f6868-6fa0-11e6-8be7-0707f3925c30.png)

![image](https://cloud.githubusercontent.com/assets/962530/18146884/161dbcfe-6fa0-11e6-9f4e-4997fd934cc3.png)

![image](https://cloud.githubusercontent.com/assets/962530/18146893/2c00386c-6fa0-11e6-9689-7815dfd37cd1.png)

![image](https://cloud.githubusercontent.com/assets/962530/18146906/397e10ae-6fa0-11e6-9788-c0b4ea6083c4.png)

**Comment by benjaminprojas** [comment]
Worth noting, this works correctly in PayPal Adaptive Payments when not using Commissions. @pippinsplugins

**Comment by michaelbeil** [comment]
Thanks for writing this up @benjaminprojas!

We will be looking into this.

**Comment by michaelbeil** [comment]
Also, another note, is that the total of the transaction is still $10 after the payment is processed through PayPal, even though the PayPal screen shows $8.

**Comment by michaelbeil** [comment]
Per a convo with @benjaminprojas:

> most likely it is how the receivers are manipulated by commissions   
> its really complicated how PayPal does everything, but I think it has to do with how commissions manipulates the amounts

**Comment by benjaminprojas** [comment]
This issue should be resolved in PayPal Adaptive Payments.  Marking as resolved. here.
