### ISSUE TITLE
Add ability to re-assign commission record(s)

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#152]
If a vendor or purchase record is accidentally deleted, the associated commission record(s) become "invalid" due to the lack of database association. There is no way to edit or delete these records from commissions table afterwards to resolve the issue. 

It would be useful to have the ability to edit the broken record(s) and re-assign the vendor and purchase IDs to solve this issue.

**Comment by pippinsplugins** [comment]
You can edit each commission and change the "user Id" field. That would reassign.

**Comment by davidsherlock** [comment]
You can't actually edit the record once the vendor (user) has been deleted, since the option isn't available within the commissions table. Additionally, there is no way to assign an order id again to a pre-existing record if deleted.

**Comment by pippinsplugins** [comment]
Ah! My bad, I thought we had already added that.

@ghost1227 let's put this in as part of the new #148 UI

**Comment by ghost1227** [comment]
@pippinsplugins unless I'm misunderstanding, this is already included in #148

**Comment by pippinsplugins** [comment]
Yes it is.

**Comment by cklosowski** [comment]
Re-opening just to get some testing done once #178 is done.

**Comment by pippinsplugins** [comment]
This looks good on issue/178 to me.

**Comment by SDavisMedia** [comment]
Seems to be working fine for me on `issue/178`. :+1:
