### ISSUE TITLE
Replace ID input with user lookup select field

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Commissions#154]
In the edit downloads screen meta box the field for assigning commission to a user requires a numerical ID to be entered. This could be made a lot easier to use by converting the field to a user search + select field. That way there would be no requirement of looking up user IDs manually elsewhere.

**Comment by pippinsplugins** [comment]
Related #93

**Comment by ghost1227** [comment]
@pippinsplugins Since this is resolved with #93 already, I propose closing this issue.

**Comment by pippinsplugins** [comment]
I agree.
