### ISSUE TITLE
Styles for rich editor is broken

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#155]
Reported here https://secure.helpscout.net/conversation/272656940/45937/?folderId=180499

If you enable EDD and Commissions only, the Rich editor is broken in EDD settings

With Commissions:
![screen shot 2016-11-04 at 4 37 40 pm](https://cloud.githubusercontent.com/assets/1390124/20025606/1cc60a8a-a2ad-11e6-980a-61b3d3a0aaa3.png)

Without Commissions:
![screen shot 2016-11-04 at 4 38 30 pm](https://cloud.githubusercontent.com/assets/1390124/20025609/260bc03a-a2ad-11e6-9dbf-09f2bec3fda1.png)

**Comment by cklosowski** [comment]
This is caused by us loading the commissions email settings into the main section, which is throwing off the email subsections. I'm creating a emails subsection for commissions which should resolve this.

**Comment by pippinsplugins** [comment]
Looks good to me!
