### ISSUE TITLE
Comission rate by user

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/EDD-Commissions#157]
Allow set a commission rate to specific user

Examples:
If you are a vendor of your own store, then you will need set your commission to 0%
For promotional purposes like, become one of the first vendors and get X% less commissions

**Comment by chriscct7** [comment]
This already exists. You can set a user's commission rate on their profile right above the paypal email field for them

**Comment by rubengc** [comment]
I looked in vendor's profile instead of user's profile, my fault

**Comment by rubengc** [comment]
I cannot set user global rate as 0

**Comment by chriscct7** [comment]
Use 0.00 instead of 0

**Comment by rubengc** [comment]
With 0.00 works, thanks @chriscct7
