### ISSUE TITLE
Account for fee adjustments in commission record

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#158]
Example, using something like Points & Rewards can add a negative fee to the cart, reducing the price page for products. However, Commissions will still record based on the full price of the product. Store owners are basically losing money.

A ticket: https://secure.helpscout.net/conversation/274061926/46211/?folderId=180504

**Comment by cklosowski** [comment]
This should be able to be done without any changes to EDD core. `EDD_Payment->cart_details` will contain any fees associated with an item, and from there you should be able to simply look for the adjustments needed before entering in a commission record.

:+1: for this moving forward.

**Comment by cklosowski** [comment]
In the case of points and rewards, I think we should be able to determine the amount a negative fee accounts for each item in the cart. We've done this before with get item discounted amount in Core, would just need to look at how we did that logic and get the total reduced amount based off a cart wide fee before striking the commission amount.

**Comment by chriscct7** [comment]
We should be able to reuse the same code in PayPal Adaptive used to split who gets how much on a percentage basis for this

**Comment by mintplugins** [comment]
This should likely be optional. In the case where a store wants to pay the full commission amount to a Vendor, they could check a box saying "ignore discounts when calculating commissions" or something like that.

**Comment by SDavisMedia** [comment]
Got another kick for this. Same original ticket.

**Comment by SDavisMedia** [comment]
If at all possible, please let's make this top priority once 3.3 is out.

**Comment by pippinsplugins** [comment]
I'm not sure this is actually a Commissions change. It's a Points and Rewards change. See https://trello.com/c/OadCVXIj/380-edd-points-and-rewards

I'm going to test locally and confirm now though.

**Comment by pippinsplugins** [comment]
Confirmed. If Jigar makes the change I requested there, the problem is resolved.

For example, a global fee like this does not affect commissions:

```php
function pw_set_admin_discount() {
    // check to see the customer is a site admin
    if( current_user_can( 'manage_options' ) ) {
	// find 20% of the total
        $amount = edd_get_cart_subtotal() * 0.20;

	// flip the 20% from a positive number to a negative number
        $amount = $amount * -1;

	// Add the fee, sending the amount, the reason printed to the front end, and the handle
        EDD()->fees->add_fee( array(
        	'amount' => $amount,
        	'label' => 'You are an admin special!',
        	'id' => 'admin_special',
        ) );
    }
}
add_action( 'init', 'pw_set_admin_discount' );
```

But a fee that specifies the `download_id` does:

```php
function pw_set_admin_discount() {
    // check to see the customer is a site admin
    if( current_user_can( 'manage_options' ) ) {
	// find 20% of the total
        $amount = edd_get_cart_subtotal() * 0.20;

	// flip the 20% from a positive number to a negative number
        $amount = $amount * -1;

	// Add the fee, sending the amount, the reason printed to the front end, and the handle
        EDD()->fees->add_fee( array(
        	'amount' => $amount,
        	'label' => 'You are an admin special!',
        	'id' => 'admin_special',
        	'download_id' => 214
        ) );
    }
}
add_action( 'init', 'pw_set_admin_discount' );
```

**Comment by pippinsplugins** [comment]
The $6.00 commission was from my global fee. The $5.00 fee was from the one with the `download_id`. No other settings were changed:

<img width="1380" alt="screen shot 2017-03-07 at 11 13 12 am" src="https://cloud.githubusercontent.com/assets/1034109/23668579/26c34a86-0327-11e7-875b-19c8bc18e6bf.png">

**Comment by SDavisMedia** [comment]
@pippinsplugins I'm a bit mixed up trying to understand a timeline here. Did you already have this conversation with Jigar over on Trello in the middle of last month? And if so, that adjustment was _not_ included in 1.4.3 (which was released a week later), right?

Just making sure. From what I'm gathering, we can expect changes in P&R 1.4.4 based on what you described above. Is that correct?

**Comment by pippinsplugins** [comment]
@SDavisMedia I started the discussion last month but it was not included in the most recent release. I'm going to push for it to be in the next point release, whereby correcting this behavior.

Let's leave this issue open until we have a confirmed fix though.

I've marked it on my todo list to write the patch for Jigar on Thursday if he hasn't alreay.

**Comment by ghost1227** [comment]
@pippinsplugins Any word on this? I'd like to see 3.3.3 closed out now that we're actively working on 3.4

**Comment by pippinsplugins** [comment]
This can be punted.

**Comment by SDavisMedia** [comment]
Can someone please team up directly with Jigar and make adjustments to either Commissions or [Points & Rewards](https://trello.com/c/OadCVXIj/380-edd-points-and-rewards) to address this issue? There's been a bit of dialogue about who should change what but it ends abruptly. Please, can someone focus on this issue?

**Comment by pippinsplugins** [comment]
I'll try and look at it first thing this week.

**Comment by cklosowski** [comment]
This issue affects Discounts Pro as well, so either it's a fix in both Points & Rewards AND Discounts Pro (and anything else that uses fees), or we fix it within commissions directly.

**Comment by mintplugins** [comment]
IMO I think it would make the most sense to do it in commissions. Not sure if related but even for payments where a normal EDD Discount code was used, the full commission is still being recorded for me.

**Comment by cklosowski** [comment]
What is your setting for how it's calculated? If it's subtotal thats before discounts. If it's totally that is after discounts.

**Comment by mintplugins** [comment]
@cklosowski Yeah I'm on subtotal - that makes sense. Thanks.

**Comment by cklosowski** [comment]
@mintplugins @SDavisMedia this is ready for testing out. I think it should take care of these issue.

**Comment by cklosowski** [comment]
On second though...quick question for you both:
Should negative fees affect the commission amount in all calculation bases, or just the ones based off `total`? For instance, `subtotal` means it calculates prior to discounts are applied, of which negative discounts are treated like.

So should negative fees only adjust the commissions amounts when `total_pre_tax` and `total` are selected?

**Comment by mintplugins** [comment]
Knowing that subtotal means - "price before discounts, fees, or taxes" I think it would be the most correct to only apply it for total_pre_tax and total - and not for subtotal. 

I think the problem is that the term "subtotal" can be somewhat ambiguous. The sub-word "total" in "subtotal" seems to indicate that multiple items are being added together to create a "total". So charging commissions based on a subtotal can be confusing to the user who might think that commissions are being charged on the entire subtotal amount - rather than the amount of a single item prior to discounts, taxes, and fees. :/

**Comment by cklosowski** [comment]
Our helper text explains it though @mintplugins `Should commissions be calculated from the subtotal (before taxes and discounts) or from the total purchase amount (after taxes and discounts)?`

**Comment by mintplugins** [comment]
Yeah but it doesn't explain that subtotal means for `only items that have commissions enabled`. 

For example:

Product 1: $50 and has commissions enabled. 
Product 2: $50 and has no commissions enabled. 

Cart subtotal: $100. Are commissions calculated on the subtotal?

**Comment by mintplugins** [comment]
This is a separate usability issue I suppose. That being said, to stay consistent I think it should only affect `total_pre_tax` and `total` - and not for `subtotal`.

**Comment by pippinsplugins** [comment]
Updated description text to `Should commissions be calculated from the item subtotal (before taxes and discounts) or from the item total (after taxes and discounts)?`.

**Comment by pippinsplugins** [comment]
@mintplugins I've updated it to only allow fees to adjust the calculation if the calculation base is _not_ subtotal.

**Comment by mintplugins** [comment]
Testing now

**Comment by mintplugins** [comment]
@pippinsplugins This is all working correctly for me. When set to subtotal the commission is generated as if there were no discount from Points and Rewards. When set to total with/without taxes it adjusts the commission accordingly. 

Could we make it so that the dropdown shows "Item's Subtotal" or "Item's Total with/without taxes" as well? I think that will help to make it more clear as well.

**Comment by pippinsplugins** [comment]
Done!
