### ISSUE TITLE
Member has private access

### ISSUE THREAD

**Issue by rahilwazir** [easydigitaldownloads/EDD-Commissions#159]
Whenever I try to open my WordPress project in PHPStorm IDE with the following plugins:
- Easy Digital Downloads
- Easy Digital Downloads - Commissions

I get an error on file [includes/admin/class-batch-commissions-payout.php](https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/admin/class-batch-commissions-payout.php#L233):
![screenshot from 2016 11 08 21 14 15](https://cloud.githubusercontent.com/assets/1818941/20106940/a364e90a-a5f8-11e6-85ab-257f57701a4d.png)

The parent class [easy-digital-downloads/includes/admin/reporting/export/class-batch-export.php](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/admin/reporting/export/class-batch-export.php#L29) has `private $file` attribute.

We should change it's scope to `protected`?

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll get that resolved.

**Comment by ghost1227** [comment]
@pippinsplugins took a look at the classes in question, and it seems to me that we have two options:

1. Make `$file` public
2. Add a method to return the value of `$file`

In either case, it appears this needs to be handled in core, not Commissions.

**Comment by pippinsplugins** [comment]
Make it `protected`. That should resolve it.

**Comment by ghost1227** [comment]
@pippinsplugins But that's still a bug with EDD core, not Commissions... as far as I can tell. Or am I missing something? Just want to make sure that I'm looking at it right (and need to open an issue on core repo to resolve this).

**Comment by pippinsplugins** [comment]
@ghost1227 Do what is necessary to get it fixed, so open a new issue / PR in core if that's what it takes.

**Comment by ghost1227** [comment]
This is ready for testing (and should be resolved) once https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5427 is closed.
