### ISSUE TITLE
Allow commissions list table to be filtered by user

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#16]
It'd be great if there was a UI option for filtering the commissions list table by a specific user.

The table can already be filtered, but there's no UI for specifying the user.

Also, the total paid / unpaid commissions need to be shown on a per-user basis somewhere.

**Comment by cklosowski** [comment]
If i'm not mistaken, this is already done. You can click on a user's name in teh commissions table to filter by them, and their total unpaid is shown at the bottom.

Do we need anything else here @pippinsplugins ?

**Comment by pippinsplugins** [comment]
I want a better UI for it.

Right now the only way to do it is to click on the user name from a row shown in the table. What if you have thousands of commissions and the user's commissions don't show on the first page?

No way to find them.

I'm thinking of a user search field like we use on the Customer screen.

**Comment by cklosowski** [comment]
:+1:

**Comment by cklosowski** [comment]
![screen shot 2015-07-08 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/1390124/8581374/32e1d274-2575-11e5-9bca-631156c9e4ac.png)
![screen shot 2015-07-08 at 1 25 25 pm](https://cloud.githubusercontent.com/assets/1390124/8581378/32ebe084-2575-11e5-88a3-8fc04a8a5190.png)
![screen shot 2015-07-08 at 1 24 44 pm](https://cloud.githubusercontent.com/assets/1390124/8581375/32e5cc26-2575-11e5-86da-138c21dd4ec6.png)
![screen shot 2015-07-08 at 1 24 58 pm](https://cloud.githubusercontent.com/assets/1390124/8581376/32e80126-2575-11e5-8ae8-adc5beed89c7.png)
![screen shot 2015-07-08 at 1 25 06 pm](https://cloud.githubusercontent.com/assets/1390124/8581377/32e85e78-2575-11e5-8c88-38876ad94152.png)

**Comment by pippinsplugins** [comment]
So sexy.

**Comment by SDavisMedia** [comment]
@cklosowski is this still working for you on `master`?

**Comment by cklosowski** [comment]
The searching for a user is deff not working. I can click on the user name, and get a list of their commissions only, but the search dropdown is not giving me the user field like in the screenshots above:
![screen shot 2017-04-05 at 9 35 06 pm](https://cloud.githubusercontent.com/assets/1390124/24738059/f3bd38ee-1a47-11e7-8ea6-39000e53955b.png)
