### ISSUE TITLE
Columns Filter Missing

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#162]
I needed to append additional data to the CSV export the vendors receive for their paid commissions, however from what I can see there are similar filters available to add the data however there is no filter available to add the actual columns.

The filter would need to go in the csv_cols() method of the EDD_Commissions_Export class. This is inside the includes/class-commissions-export.php file of the commissions plugin.

**Comment by pippinsplugins** [comment]
There are filters in the base classes that `EDD_Commissions_Export` extends :)

**Comment by davidsherlock** [comment]
Thanks @pippinsplugins, this issue can be closed.
