### ISSUE TITLE
Empty CSV Export

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#163]
Within the FES vendor earnings tab, the vendors are able to export "Paid Commissions". However if a vendor selects a month with no commissions a blank file is downloaded.

Better logic would be to only show the months/years valid to that vendor (with past paid commissions) and skip downloading a redundant empty CSV file.

**Comment by pippinsplugins** [comment]
I haven't looked into it yet but I suspect this is a bug in FES, not Commissions since the Vendor reports are built via FES.

**Comment by davidsherlock** [comment]
I believe this has been fixed recently with the move to custom tables, this issue can be closed.
