### ISSUE TITLE
Hooks for new fields

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/EDD-Commissions#171]
Hi

I need (by EU law) record the commissions amounts I paid to vendors in EUR for accounting

I know this is a specific feature so I am developing this by myself, but when I tried to add new columns on commissions list and on commision edit page I did not found any hook to add new fields

I know this is precipitate but, could be possible to add this hooks as soon as possible? (accounting limit date is on January 20th :/)

**Comment by rubengc** [comment]
To make it more quickly I will add where hooks could be:

On includes/admin/edit.php inside <tbody> could be here an action with `edd_commission_form_fields_top` and `edd_commission_form_fields_bottom`

On includes/EDD_C_List_Table.php could be:
- on get_columns() a filter with `manage_edd_commissions_columns`
- on column_default() a filter with `manage_edd_commissions_custom_column`

**Comment by davidsherlock** [comment]
@rubengc, can you provide more background on this please? I am not following this feature request exactly. 

I see your store is in US dollars, you need to store the current EU conversation rate for the commissions paid?

**Comment by rubengc** [comment]
Yes, any transaction need to be converted in EUR (with the conversion value of the date when this transaction happens)

I have a plugin that handles this conversion on payments (and now I have it on commission) but to make It work(or at least make meta fields visible on lists and editables pm editado view) I need add those hooks

I have a PR ready but need confirmation from a member of EDD team 

This hooks are a common need to anyone that wants extends EDD commissions functionality

**Comment by davidsherlock** [comment]
@rubengc, I understand now. So the conversion value (rate) and calculatedamount are stored with this extension?

I actually did something similar myself and wrote a function to store the actual item sale price (after discounts/taxes) on a per commissions basis with each new commission record created. So I agree with you here, this would be useful to have.

Are you going to post your add-on on GitHub? I will happily test it.

**Comment by pippinsplugins** [comment]
I've milestoned this for 3.3 so we can get it in.

**Comment by davidsherlock** [comment]
I second this @pippinsplugins! This would be really useful for both myself and @rubengc as we are building invoicing systems for handling commission payouts.

**Comment by davidsherlock** [comment]
Before I forget, also having hooks for the FES/vendor front-end tables as well.

**Comment by ghost1227** [comment]
@pippinsplugins At a glance, this looks good to me. Unless you want to change any of the names he chose, I say it's good to go, sans a refresh against 3.3

**Comment by pippinsplugins** [comment]
@ghost1227 go ahead  and refresh against 3.3 then I"ll take a look at it.

**Comment by ghost1227** [comment]
@pippinsplugins refreshed

**Comment by ghost1227** [comment]
@pippinsplugins Fixed latest round of merge conflicts
