### ISSUE TITLE
Commission % on bundle renewals is wrong

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#173]
If you make a bundles product (must be bundle) buy it, and then renew it, and use the shortcode for commissions, on the renewal order if the order costs $15, and the coission amount is $10, the commissions column correctly shows $10 but the percentage column always is the number in the commission amount column and then a percentage sign, so in this example 10% not the correct 66.7%.

If the order amount is $20, and the commission awarded percent is set to $15, the commissions amount column correctly shows $15 but the percentage column says 15% not 75%

Replicated this on a couple different FES testing sites using the FES dummy data generator tool.

**Comment by chriscct7** [comment]
Sidenote, if the commission amount is over $100, the commission percentage will literally show like 110% and stuff. I think somewhere the function used to get this percent is pulling the amount and just appending a percent sign to it for renewals of bundles

**Comment by chriscct7** [comment]
eddc_get_recipient_rate() seems to be saving the bad percentage value into the commissions meta info meta key

**Comment by chriscct7** [comment]
The more I look at this the more I don't understand how this function is handling flat vs percentage based commission amounts. If the commission rate is defined on the product in percentage then returning whatever that number is and appending a % sign to it is okay. But if it's a flat amount I don't see how this is calculating the percentage of the commission vs the order total and returning that number. Not sure why this works at this point for any flat based commission product, instead of just being broken on renewals of bundle products

**Comment by mintplugins** [comment]
@chriscct7 I can't seem to replicate what you are saying. I made a bundle and renewed it as you outlined. The cost is $15 and the flat rate is $10. I also tested in percentage mode to be thorough, with the amount still at $15 and the rate at 10%. 

If I understand this issue correct (which, admittedly I'm struggling to understand), this is resolved in https://github.com/easydigitaldownloads/EDD-Commissions/issues/221 (where we format the rate for output correctly in the shortcodes).

**Using Flat Rate commissions:**
Shortcode shows correct amount before renewal:
<img width="603" alt="screen shot 2017-04-27 at 4 15 48 pm" src="https://cloud.githubusercontent.com/assets/1638128/25502543/01088b38-2b65-11e7-9c44-2e5ba2faa771.png">

After Renewal through SL, shortcode shows correct amount for renewal as well:
<img width="565" alt="screen shot 2017-04-27 at 4 22 23 pm" src="https://cloud.githubusercontent.com/assets/1638128/25502706/b9eff30c-2b65-11e7-905f-b5c0fe5569dc.png">

**Using percentage based commissions:**
Shortcode shows correct percentage and amounts before renewal:
<img width="603" alt="screen shot 2017-04-27 at 4 24 28 pm" src="https://cloud.githubusercontent.com/assets/1638128/25502780/122bd1a8-2b66-11e7-99b9-8053e8284637.png">

Shortcode shows correct percentage and amounts before renewal:
<img width="576" alt="screen shot 2017-04-27 at 4 28 33 pm" src="https://cloud.githubusercontent.com/assets/1638128/25502959/947be594-2b66-11e7-9fd2-2ead3591a28d.png">

If I have tested incorrectly or not addressed your concerns in my replication attempts, please describe them again as clearly and concisely as possible and I'll be happy to try and replicate again.
