### ISSUE TITLE
Bring order to our file / folder structure

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/EDD-Commissions#178]
We just went through this with Software Licensing, but Commissions is just as bad, if not worse.

**Comment by ghost1227** [comment]
@pippinsplugins Thoughts?

**Comment by pippinsplugins** [comment]
Yes let's do it.

**Comment by ghost1227** [comment]
NOTE: Just as we did with the SL issue, this will be the last issue finished before release.

**Comment by pippinsplugins** [comment]
@ghost1227 let's go ahead and delete the `scheduled-payouts.php` file. That's never been used and won't be.

**Comment by pippinsplugins** [comment]
Same thing with the `masspay` folder.

**Comment by ghost1227** [comment]
@cklosowski Looks like manual commissions doesn't take into account the changes we made in https://github.com/easydigitaldownloads/EDD-Commissions/issues/110. Added a $10 flat commission and it displayed as a percentage

**Comment by ghost1227** [comment]
Nevermind, I withdraw that issue. Looks like i was looking at the irrelevant rate column.

**Comment by ghost1227** [comment]
Per discussion on slack, as soon as final test suite is finished, this issue is cleared.

**Comment by ghost1227** [comment]
Tests are passing!
