### ISSUE TITLE
Tiered Commission Rates

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#181]
An automatic tiered commission rate system similar to what AffiliateWP has (https://affiliatewp.com/add-ons/pro/tiered-affiliate-rates/) would be awesome to have for.

**Comment by davidsanders** [comment]
@pippinsplugins / @davidsherlock or at the user role level, which ever is easiest.

**Comment by pippinsplugins** [comment]
Related #132

**Comment by cklosowski** [comment]
I think this will be best served once we get EDD's redesign of the Variable Pricing structure done and solidified so the styles are in EDD Core. Right now we'd just be making a mess of the interface, but once we've got the work from EDD 2704 in place, we can make this a MUCH more manageable interface.

**Comment by scottlewis01** [comment]
Hi all.  My partner and I are working on a digital media site and working with the WooNinja team on some basic EDD customizations.  This tiered commissions feature is required before going live and we are weighing our needs/desires to have them create this feature or wait until 3.5 has it built in.  Any idea of timeline on that or ability to push this to next release if we provide dev money or time?  Please advise.

**Comment by pippinsplugins** [comment]
@scottlewis01 there's not ETA right now. It definitely will not be in 2017.

**Comment by davidsherlock** [comment]
@scottlewis01, I am aware this issue is old but just giving you a heads up that I am building this plugin at the minute and will be releasing it this week if you still need it.

**Comment by davidsherlock** [comment]
This issue can be closed, I built this as a 3rd party plugin: http://sellcomet.com/downloads/tiered-commission-rates/
