### ISSUE TITLE
3.3 Branch is generating free commissions.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Commissions#196]
If a product is $0 and has commissions enabled, $0 commissions are enabled. Previously they were not. I believe that the correct behaviour for a $0 product would be to have no commissions generated upon purchase.

Or rather, if a commission in $0, I don't believe it makes sense to generate it.

**Comment by ghost1227** [comment]
@mintplugins This is actually part of issue #93. The way I was saving commissions was resulting in forced $0 commissions. Closing this since it's actually part of the other issue.

**Comment by mintplugins** [comment]
Cool thanks - just wanted to log it but wasn't sure where.
