### ISSUE TITLE
Intermittent "unpaid" commission statuses

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#197]
Using the latest version of commissions plugin I have walked into a recurring issue where commission records aren't being properly marked as paid after the payout file is exported. 

There are no apparent links to what records aren't being marked as paid and which ones are unpaid, it seems to in most cases by the older commissions from the month not being marked as "paid".

I can post up a video to demonstrate what is happening for clarity (if required).

**Comment by davidsherlock** [comment]
Here is a few "guess" what is causing this (i haven't looked in depth into the commissions code, so just an idea).

A race condition is happening with the speed of the button clicks between the "Generate Payout File" and "Mark As Paid". If you hit the "Mark As Paid" quickly after hitting downloading it seems to happen more often where it misses whole pages of commissions.  Something in the "Delay" between processes seems to be causing this.

**Comment by davidsherlock** [comment]
Found the bug @pippinsplugins, here is the problematic function:

```
	function process_bulk_action() {

		$ids = isset( $_GET['commission'] ) ? $_GET['commission'] : false;

		if ( !is_array( $ids ) )
			$ids = array( $ids );

		foreach ( $ids as $id ) {
			// Detect when a bulk action is being triggered...
			if ( 'delete' === $this->current_action() ) {
				wp_delete_post( $id );
			}
			if ( 'mark_as_paid' === $this->current_action() ) {
				eddc_set_commission_status( $id, 'paid' );
			}
			if ( 'mark_as_unpaid' === $this->current_action() ) {
				eddc_set_commission_status( $id, 'unpaid' );
			}
			if ( 'mark_as_revoked' === $this->current_action() ) {
				eddc_set_commission_status( $id, 'revoked' );
			}
			if ( 'mark_as_accepted' === $this->current_action() ) {
				eddc_set_commission_status( $id, 'unpaid' );
			}
		}
	}

```

The problem exists due to the fact that if you apply bulk actions such as setting all commission records to "Unpaid" on page 4 or similar, then run the export route and click "mark as paid" this page of commissions (the last modified) isn't marked as paid because the way WordPress handles the sessions/requests.

**Comment by davidsherlock** [comment]
A simple fix would be to force a redirect back to `wp-admin/edit.php?post_type=download&page=edd-commissions` once a batch process has been performed.

**Comment by pippinsplugins** [comment]
@ghost1227 can you look into this please?

**Comment by davidsherlock** [comment]
@pippinsplugins, any word on this one? It's a WordPress query argument issue I believe, but it's caught me out a few times.

**Comment by cklosowski** [comment]
Since moving to the custom tables, is this still an issue @davidsherlock.

**Comment by davidsherlock** [comment]
@cklosowski, no longer an issue this can be closed now.
