### ISSUE TITLE
$0 Commissions if no rate exists.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Commissions#198]
If no commission rate is entered for the product, user, and site default, a $0 commission is generated. We should prevent $0 commissions from being generated as they could be confusing and don't serve any use to the site owner.

**Comment by rubengc** [comment]
I got commissions of $0 on users with 0 rate so no commission should be generated here

**Comment by pippinsplugins** [comment]
Have we recorded 0.00 commissions in the past? If so, this needs to be introduced with a setting as some people may be using them for other tracking purposes (we see it in AffiliateWP, for example, a lot).

**Comment by cklosowski** [comment]
I am using a `$0.00` commission as a method of tracking conversion between two of my own sites.

**Comment by ghost1227** [comment]
That makes sense! I'll change that.

**Comment by pippinsplugins** [comment]
Let's add a radio button (`yes` being default) for `Allow $0.00 commissions?`

**Comment by ghost1227** [comment]
@pippinsplugins Try that

**Comment by pippinsplugins** [comment]
@ghost1227 Look good but I'd like a few changes. See the review on the PR.

**Comment by ghost1227** [comment]
@pippinsplugins Changes submitted

**Comment by pippinsplugins** [comment]
@ghost1227 I cannot get 0.00 commissions to get recorded at all, regardless of the settings I use.

**Comment by pippinsplugins** [comment]
Definitely enabled.
<img width="1206" alt="screen shot 2017-04-17 at 2 55 57 pm" src="https://cloud.githubusercontent.com/assets/1034109/25102417/07e38d48-237e-11e7-911a-286d04210367.png">

**Comment by mintplugins** [comment]
For me, if the price of the product is $0 and the commission rate is 50%, it isn't working

Not working (no commission is generated): 
- Price is $0
- Commission is 50%

Is working ($0 commission is generated):
- Price is $5
- Commission rate is 0%

**Comment by pippinsplugins** [comment]
@ghost1227 could you take another look?

**Comment by ghost1227** [comment]
@pippinsplugins I still can't get it to fail, but I'm not understanding @mintplugins if a product is $0 and has a 50% commission, 50% of $0 IS $0, so it SHOULDN'T record a commission... and with a $5 commission at 0% I can't get it to record a commission (which, again, it shouldn't to my understanding)

**Comment by pippinsplugins** [comment]
@ghost1227 Show me _all_ of your configurations and releveant screenshots. Phil and I replicated super easily so something on your end must be off. Or you have non-pushed code.

**Comment by ghost1227** [comment]
Ok... I've been working through this with @mintplugins and I've been able to replicate the issue in certain situation... and track down the cause. The reason it's not recording (at least in his situation) is because the `eddc_calculate_payment_commissions` function is returning an empty array. As a result, it's never reaching the new code we added to track $0 commissions.

**Comment by ghost1227** [comment]
@pippinsplugins I was testing in a very specific set of circumstances (the one that I originally used to write it). in that circumstance, it works as expected. with the (more common) scenario that you and @mintplugins tested, the plugin isn't actually reaching our new code... it's bailing before it ever has a chance to record due to `eddc_calculate_payment_commissions` returning an empty array.

**Comment by ghost1227** [comment]
Specifically, it's this block that's causing it to bail: https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/commission-functions.php%23L112-L115

**Comment by pippinsplugins** [comment]
@ghost1227 that link gives me a 404.

**Comment by ghost1227** [comment]
@pippinsplugins `%23` should be `#`... github breaks its own links on post.

**Comment by pippinsplugins** [comment]
Testing again!

**Comment by pippinsplugins** [comment]
Works perfectly!
