### ISSUE TITLE
Payment Thresholds for Mass Pay

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#20]
https://easydigitaldownloads.com/support/topic/threshold-payout/

**Comment by christ0ph3r** [comment]
Would love to see this :)

**Comment by pippinsplugins** [comment]
We do this in AffiliateWP and it works great.

**Comment by cklosowski** [comment]
Once we merge in #44, I'll build this part out.

**Comment by pippinsplugins** [comment]
Works great!
