### ISSUE TITLE
Commission Edit Screen Hooks

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#203]
As per https://github.com/easydigitaldownloads/EDD-Commissions/issues/171, can the following hooks be added to allow new rows to be added to the edit commissions screen? They seem to be missing from the latest beta. 

Hooks currently exist outwith the table, but not within the table itself.

```
<?php do_action( 'edd_commission_form_fields_top', $commission_id ); ?>
<?php do_action( 'edd_commission_form_fields_bottom', $commission_id ); ?>
```

**Comment by pippinsplugins** [comment]
@ghost1227 could you please get these added?

**Comment by ghost1227** [comment]
@pippinsplugins Our standard for Commissions is `eddc_` not `edd_commission_`. I'd recommend using the standard to maintain consistency. Thoughts?

**Comment by pippinsplugins** [comment]
Yes, maintain the standard.

**Comment by ghost1227** [comment]
@pippinsplugins How's that?

**Comment by pippinsplugins** [comment]
Looks good.
