### ISSUE TITLE
User ID missing from Payout file

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#204]
As part of the new commissions 3.3 wasn't the Used ID supposed to be included in the payout file generated? Since PayPal supports additional columns for "reference" numbers and alike.

This makes it easier for vendors to identify payments they receive.

**Comment by mintplugins** [comment]
To confirm, are you seeing this happen on the 3.3 branch? Do you know which github issue number this was tackled in?

**Comment by davidsherlock** [comment]
@mintplugins, yes using the latest beta version. I am unable to recall the exact issue number, but will look later on tonight for it.

**Comment by pippinsplugins** [comment]
I noticed this when generating the payout file on easydigitaldownloads.com last week. We run the beta there and did _not_ have the user ID included.

**Comment by ghost1227** [comment]
@pippinsplugins ready for re-review

**Comment by pippinsplugins** [comment]
Merged!
