### ISSUE TITLE
Missing Total Unpaid from commissions list table

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#209]
<img width="547" alt="3f51bca88a45a31e0407b854778a5592 _image 2017-03-29 at 8 41 47 am" src="https://cloud.githubusercontent.com/assets/2359131/24463966/3d24fd50-145d-11e7-93cb-c9ab0b00b3ed.png">

A customer who uses it noticed that it was gone. Pretty sure it was just an oversight. So we should add it back.

**Comment by SDavisMedia** [comment]
Just got another ticket about this. Never knew people even noticed that.

**Comment by pippinsplugins** [comment]
@ghost1227 can we get a PR for this tomorrow please?
