### ISSUE TITLE
Product variation database storage improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#210]
At the minute the commissions plugin stores the product variation as simply a string within the database, corresponding to the commission ID.

While this is effective for the purposes of commissions table display, it isn't an ideal method if you need to use it for comparison purposes with the original cart array. I propose the product variations are stored using the same method as the order history stores product variations, so comparison is more accurate on on a 1-to-1 basis.

Ideally to make the commissions data storage more accurate, the entire cart array line would be stored on a commission basis to make it easy to lookup and compare if you need to figure out the "service fees" for the marketplace earnings.

**Comment by pippinsplugins** [comment]
@davidsherlock we'll be moving all commission storage to a custom table soon and it'll be made easier then: https://github.com/easydigitaldownloads/EDD-Commissions/issues/134

**Comment by davidsherlock** [comment]
This can be closed, as custom tables fixed this issue.
