### ISSUE TITLE
User search field not working on commissions list table

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#214]
Added in #16, the search field no longer seems to be working correctly to filter the commissions list table by user.

Reported: @SDavisMedia 
Confirmed: @cklosowski

**Comment by ghost1227** [comment]
@cklosowski My fault it was removed... it somehow didn't get migrated when I did the overhaul. Readded

**Comment by SDavisMedia** [comment]
Outstanding. Working well for me now. :+1:

**Comment by mintplugins** [comment]
If there is no matching search results, you will get error here. Re-opening:
<img width="1293" alt="screen shot 2017-04-27 at 3 12 05 pm" src="https://cloud.githubusercontent.com/assets/1638128/25500233/441c08a4-2b5c-11e7-8449-7202174ba6ce.png">

**Comment by mintplugins** [comment]
Working now! Thanks @ghost1227
