### ISSUE TITLE
Revoked Dates

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#219]
If commissions are marked as either paid or revoked, it would be useful to keep track of both these dates independently for accounting/transactional purposes. Similarly being able to edit/update these dates would be beneficial.

**Comment by cklosowski** [comment]
Paid dates will be part of the `release/3.4` when we're adding the new table which has a `date_paid` column. So that makes this simply a 'date_revoked' somehow logged.

**Comment by davidsherlock** [comment]
I don't believe this is worth adding after-all, this issue can be closed.
