### ISSUE TITLE
Specific downloads don't have user_id in eddc_get_download_ids_of_user

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/EDD-Commissions#226]
The function `eddc_get_download_ids_of_user` seems to not always have a commissions settings array attached - even though commissions are enabled. This could be leftover data in my test environment due to a separate issue in EDD core which was preventing users from properly saving. 

The error message appears on the customer profile in admin:
```
 Notice: Undefined index: user_id in /Users/philjohnston/Documents/wps/edd2.dev/wp-content/plugins/EDD-Commissions/includes/commission-functions.php on line 364
```

If I update the download in question, it then makes the error go away. 

Before re-update of product, the returned array is:
```
stdClass Object
(
    [post_id] => 37
    [settings] => a:1:{s:4:"type";s:10:"percentage";}
)
```

After re-update of product it is:
```
stdClass Object
(
    [post_id] => 37
    [settings] => a:4:{s:4:"type";s:10:"percentage";s:5:"rates";a:1:{i:1;a:2:{s:7:"user_id";s:1:"4";s:6:"amount";s:2:"20";}}s:7:"user_id";s:1:"4";s:6:"amount";s:2:"20";}
)
```

Perhaps we should do an "empty" check here to be sure the data exists?

**Comment by mintplugins** [comment]
While looking at this I also noticed a bug in the same function (`eddc_get_download_ids_of_user`) where it would include a product for a user even if commissions had been disabled for that product. This means that commissions used to be on and the user has commissions data that exists in the post, but the site owner has since disabled commissions. In this PR, we now correctlyremove those disabled commissions products from the list of products this user is linked to.

**Comment by ghost1227** [comment]
👍 This looks good!

**Comment by mintplugins** [comment]
Issue with this in PHP5.3
```
Fatal error: Can’t use function return value in write context in /home/travis/build/easydigitaldownloads/EDD-Commissions/includes/commission-functions.php on line 369
```
