### ISSUE TITLE
Renewals should be noted

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#23]
As a vendor, right now there is nothing distinguishing a commission from a renewal and a commission from a new sale. This makes it very difficult to tell if when you get a commission lower than expected, if a coupon was used, if its a renewal, or the commission wasn't calculated correctly. We should distinguish renewal commissions better, maybe even their own renewal table, so vendors can keep track of how much they are doing in new sales vs renewals

**Comment by cklosowski** [comment]
going to wait for #44 to go into this as I'll be updating the `eddc_get_commissions()` method again, to support the `is_renewal` meta item.

**Comment by cklosowski** [comment]
Will this do?
![screen shot 2015-07-07 at 5 17 01 pm](https://cloud.githubusercontent.com/assets/1390124/8560402/04d41a26-24cc-11e5-8e37-6cf76590fa11.png)

**Comment by pippinsplugins** [comment]
Looking good.

Can you please also add a flag to the REST API data?

**Comment by chriscct7** [comment]
Can we make the unpaid and paid shortcodes filterable to renewals only or new sales only or both via a shortcode param.

**Comment by pippinsplugins** [comment]
Perhaps in the future, not for this release.
