### ISSUE TITLE
_edd_commission_status not updated on status change

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#230]
I did a fresh install of WordPress, EDD (2.7.7), Commissions (3.3.2) and nothing else on a local development setup. I created two products and associated them with a commission of 50% each. I put through an order and the commissions were recorded correctly. I then marked them as paid and checked the postmeta for each of the commission records. In both cases the postmeta was marked as "unpaid" yet the table showed paid due to the way commissions status uses the terms taxonomy to find the actual status. Changing to "Revoked" had the same effect.

My thoughts are `_edd_commission_status` is obsolete now or exists purely for backwards compatibility.

**Comment by pippinsplugins** [comment]
@davidsherlock the status isn't stored in post meta anymore and exists only for backwards compat. We don't set it any more, but we do filter `get_post_meta()` and `update_post_meta()` calls for it to re-route those to the taxonomy term that we use.
