### ISSUE TITLE
Tax remittance calculation base addition

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#233]
There are business instances where the tax burden is shifted from the marketplace to the vendor, however there is currently no way to remit the 'whole' tax amount collected on the sale (the current methods will split the tax equally between site and vendor or retain it). 

An additional calculation base option could be added to remit the full item tax amount along with the commission base amount.

**Comment by pippinsplugins** [comment]
@davidsherlock could you please provide a concrete example of what you need to do?

**Comment by davidsherlock** [comment]
Apologies @pippinsplugins, I should have been clearer on this one. 

Here is an example to better explain (assume tax is set exclusively and no coupon codes are used on the order):

Item price: £12
Tax (20%): £2.40
Total: £14.40

For simplification purposes, using the "total without taxes" base calculation setting at 50% commission rate would result in commission being recorded at £6 with the 2.40 tax being remitted/collected by the site owner for the tax authorities. 

However the setting I propose would effectively "pass-on" the tax responsibility to the vendor and record a commission amount of £8.40 to the vendor. Does this make sense?

**Comment by davidsherlock** [comment]
This can be closed, I will write a code snippet (or plugin) for this one.
