### ISSUE TITLE
Commission Notifications email additional shortcodes

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#237]
I run a 'pure' marketplace where the contract of sale is directly between the buyer and seller, due to this It would be great if some additional shortcodes were added to the "Commission Notifications" email as follows:

- {commission_id} - The ID of the commission
- {item_price} - The item "sale price".
- {item_tax} - The item tax collected.
- {discount_codes} - any discount codes _ONLY_ applied to this specific item.

**Comment by cklosowski** [comment]
I'm good with adding Commission ID, Item Price, and Item Tax with 3.4, but I want to hold off on the discount codes for now for 2 reasons:
1) With the addition to after payment actions, I want to find a way to delay sending these emails, and the discount code lookup for validity on a product is going to be expensive looping, which can delay the checkout process. By doing it on the delayed action we can save the user that load time:
2) We have an open issue where we can simply pass in a discount code and product ID to see if it is valid. Meaning a simple foreach loop of the downloads and discounts used and we know which ones worked on which products, right now that's a pretty expensive set of code.
