### ISSUE TITLE
Check needed to ensure amount key exists in _edd_commission_settings array

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Commissions#238]
Right [here](https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/commission-functions.php#L286) we're assuming the `amount` key exists in the `_edd_commissions_settings` array but it doesn't always. Specifically if a vendor adds a product, [only the `user_id` key is added](https://github.com/easydigitaldownloads/edd-fes/blob/master/classes/forms/submission.php#L153) to that meta value. The other two keys (`amount` and `type`) are only set when the download is [saved from the backend](https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/admin/metabox.php#L262).

I think in the first link above, we should check to see if the key exists first. Maybe use `eddc_calc_commission_amount()` or something.

**Comment by cklosowski** [comment]
@brashrebel try that out.

**Comment by brashrebel** [comment]
Looks good to me. Just did some testing and no errors were observed.
