### ISSUE TITLE
Update POT file

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#245]
I know it's missing at least one string: https://github.com/easydigitaldownloads/EDD-Commissions/blob/0d28a39f97ad3ad5fd20a040008bc19a5fc06522/includes/admin/settings.php#L71

**Comment by cklosowski** [comment]
There we go @SDavisMedia. Not only did it have missing strings, but it hadn't been refreshed since the restructuring of the plugin itself...so this should take care of things
