### ISSUE TITLE
Manual commissions recorded for `Vendor Dashboard` if no download set

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Commissions#257]
When adding a commission from the admin, if you do not select a download ID, the commission is recorded for `Vendor Dashboard`

<img width="967" alt="screenshot 2017-06-18 15 39 25" src="https://user-images.githubusercontent.com/52581/27257873-5f0a6274-543c-11e7-8088-66cfc070645c.png">

**Comment by cklosowski** [comment]
Can you confirm this on the release/3.4 branch as well?

**Comment by amdrew** [comment]
@cklosowski Yes, happens on release/3.4 also

**Comment by cklosowski** [comment]
👍
