### ISSUE TITLE
Improve validation and abilities of Commission Add/Edit screens.

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Commissions#258]
**Completely hijacking this issue as it's needed**
The Add commission and Edit Commission views were lacking some validation and missing entire fields that should be editable like the status, date paid, and date created.

This issue has been upgraded to include a bunch of improvements including:
- Allow setting the status when adding a commission
- Allow setting/editing the date_created
- Allow setting/editing the date_paid
- Validate that a download_id is specified when adding

**Comment by cklosowski** [comment]
@davidsherlock Take a look here, it may have some improvements that you requested in #220 and #219 (originally asked for date_paid)

**Comment by pippinsplugins** [comment]
This has been merged in through #260. Working great for me!
