### ISSUE TITLE
Generated commission uses flat amount as rate percentage

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Commissions#259]
release/3.4

If I enter a manual commission from the admin and choose a `flat` type with an `amount`, the generated commission shows a percentage rate with the amount entered. Shouldn't the rate be empty since I didn't enter a 502% rate?
 
<img width="724" alt="screenshot 2017-06-19 09 48 39" src="https://user-images.githubusercontent.com/52581/27264526-81595d06-54d4-11e7-890f-7f66e4a93287.png">

<img width="1373" alt="screenshot 2017-06-19 09 48 48" src="https://user-images.githubusercontent.com/52581/27264525-812e91a2-54d4-11e7-9fc3-e78eb32a64d5.png">

**Comment by cklosowski** [comment]
It's falling back to global since no rate was round. The Rate should be 502, along with the type of `flat`. I'll look into that.

**Comment by cklosowski** [comment]
As a note, the actual commission is still the correct rate type. If you click into the `View` it shows correct, it's just the list table `type` detection is looking at. I'll fix it along side #258

**Comment by pippinsplugins** [comment]
@cklosowski this looks good and appears to be working for me. Only issue is that the redirect after creating the subscription fails and I get an error screen. It's failing because this line 82 of commission-filters.php is getting triggered:

```php
		case '_edd_commission_payment_id':

			$value = $commission->payment_id;

			if ( $show_notice ) {
				// Throw deprecated notice if WP_DEBUG is defined and on
				trigger_error( __( 'The _edd_commission_payment_id postmeta is <strong>deprecated</strong> since EDD Commissions 3.4! Use the EDD_Commission object to get the relevant data, instead.', 'edd_sl' ) );

				$backtrace = debug_backtrace();
				trigger_error( print_r( $backtrace, 1 ) );
			}

			break;
```

**Comment by pippinsplugins** [comment]
Working on tracking it down and fixing it.

**Comment by pippinsplugins** [comment]
Ok that error is unrelated. It's getting triggered after the redirect is completed and is coming from the list table. See https://github.com/easydigitaldownloads/EDD-Commissions/issues/134#issuecomment-313155675

This is good to go, merging.
