### ISSUE TITLE
Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/EDD-Commissions#263]
`release/3.4`

Right after adding a manual commission in the admin I get:

```
Notice: Trying to get property of non-object in /wp-content/plugins/EDD-Commissions/includes/email-functions.php on line 133
```
```
Warning: Cannot modify header information - headers already sent by (output started at /wp-content/plugins/EDD-Commissions/includes/email-functions.php:133) in /wp-includes/pluggable.php on line 1210
```

**Comment by cklosowski** [comment]
@amdrew that's odd b/c that's getting the user object, which means that you didn't have a user ID when you added it, but a user ID is required for a commission. This is in the emails that get sent, so we can define a name and replace `{name} and {fullname}`.

Are you adding a commission without an ID?

**Comment by cklosowski** [comment]
As a note, I cannot replicate this.

**Comment by amdrew** [comment]
@cklosowski Figured it out. The `edd_commissions` DB table did not exist for me. Just saw the upgrade notice now however and ran it, which created it and now the errors are gone.
