### ISSUE TITLE
Decimal places not supported in commission rates

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#277]
It's not currently possible to set up commission rates that include a decimal, such as 12.5%. When doing that, the product edit screen retains the `.5` but the list table shows only `12%` and all calculations are done at `12%` instead of `12.5%`.

**Comment by pippinsplugins** [comment]
PR submitted for this!

To replicate:

- on `master` setup a product with a commission rate of `12.5%`
- purchase the product
- commission rate will show as `12` after commission record is created

To test fix:

- on `issue/277` load the admin area (triggers upgrade routine)
- purchase same product
- commission rate and amount should now be correctly based on 12.5%

**Comment by sunnyratilal** [comment]
Issue replicated on `master` and fix confirmed on `issue/277` 👍

**Comment by cklosowski** [comment]
Just fixed up the unit tests so that this doesn't make them fail, It was failing with an expected value of `3` and `0`, but seeing `3.0` and `0.0`. And since we're using `assertSame` they have to be identical in type and value.
