### ISSUE TITLE
get_bulk_actions array filter suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#279]
Within `EDD_C_List_Table.php` I wanted to add a new bulk action to the drop-down for my new commission statuses (_pending_ and _awaiting clearance_), however, there is no filter available for the get_bulk_actions array. Can this be added, please?

Filters are available for the per row actions, but not the bulk actions.

**Comment by cklosowski** [comment]
This seems like a fair request. Milestoning for the 3.5 release, unless a PR comes in proir to that to include in a point release.

**Comment by davidsherlock** [comment]
This can be closed, as I submitted PR that has been merged and allows filtering.
