### ISSUE TITLE
eddc_get_commissions posts_where filter suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#280]
Much like the `edd_get_payments` function, it would be useful to have a filter available so the commission records can be easily filtered like get_payments method.

For example, I wanted to conditionally (via a filter) filter commissions for the past 7 days but no filter exists other than hard coding a custom query.

**Comment by cklosowski** [comment]
@davidsherlock Commissions is no longer a custom post type since 3.4...so a `posts_where` filter is useless.

The `EDDC_DB` class actually supports using a date with an array that contains a start and end.

`EDDC_DB::get_commissions( $args )` runs `EDDC_DB::parse_where` which runs this logic:

```
		// Created for a specific date or in a date range
		if( ! empty( $args['date'] ) ) {

			if( is_array( $args['date'] ) ) {

				if( ! empty( $args['date']['start'] ) ) {

					$start = date( 'Y-m-d H:i:s', strtotime( $args['date']['start'] ) );

					$where .= " AND `date_created` >= '{$start}'";

				}

				if( ! empty( $args['date']['end'] ) ) {

					$end = date( 'Y-m-d H:i:s', strtotime( $args['date']['end'] ) );

					$where .= " AND `date_created` <= '{$end}'";

				}

			} else {

				$year  = date( 'Y', strtotime( $args['date'] ) );
				$month = date( 'm', strtotime( $args['date'] ) );
				$day   = date( 'd', strtotime( $args['date'] ) );

				$where .= " AND $year = YEAR ( date_created ) AND $month = MONTH ( date_created ) AND $day = DAY ( date_created )";
			}

		}
```

**Comment by cklosowski** [comment]
Furthermore, since `eddc_get_commissions` uses this class to get the data, you can pass in this `date` array into `eddc_get_commissions` as well.

**Comment by davidsherlock** [comment]
@cklosowski, my apologies - I forgot about this!

Could you tell me what i am doing wrong here with my query? I am trying to get all the commissions for the last day with the status of "pending" (a custom status I set on the records).

```
$args = array(
'status' => 'pending',
'number' => -1,
'output' => 'edd_commissions',
'query_args' => array(
'date_query' => array(
     array(
         'after'     => 'midnight 1 days ago',  // or '-2 days'
         'inclusive' => true,
     ),
 ) ),
);

$commissions = eddc_get_commissions( $args );

var_dump ( $commissions );
```

For some reason this is returning all the records, which is causing a headache because my project is almost complete if I can get this working :(

**Comment by cklosowski** [comment]
@davidsherlock b/c you are treating it like a `WP_Query`, which it is not.

```
$args = array(
    'number' => -1,
    'status' => 'pending',
    'date' => array( 
        'after' => 'midnight 1 days ago',
    ),
);
```

**Comment by davidsherlock** [comment]
@cklosowski, does this query the commission `date_created` field date or the database post date? For some reason the query is still returning commissions that were updated with new date_created dates but are beyond are the query.

**Comment by davidsherlock** [comment]
For clarity here is the record that is coming back:

```
array (size=1)
  0 => 
    object(EDD_Commission)[8639]
      protected 'id' => string '53' (length=2)
      protected 'user_id' => string '1' (length=1)
      protected 'description' => string 'dev-email@flywheel.local - Service 1' (length=36)
      protected 'download_variation' => string '' (length=0)
      protected 'rate' => string '50' (length=2)
      protected 'type' => string 'percentage' (length=10)
      protected 'amount' => string '13.340000' (length=9)
      protected 'currency' => string 'GBP' (length=3)
      protected 'download_id' => string '377' (length=3)
      protected 'payment_id' => string '381' (length=3)
      protected 'status' => string 'pending' (length=7)
      protected 'cart_index' => string '0' (length=1)
      protected 'is_renewal' => boolean false
      protected 'price_id' => string '0' (length=1)
      protected 'date_created' => string '2017-10-01 00:00:00' (length=19)
      protected 'date_paid' => string '0000-00-00 00:00:00' (length=19)
      private 'pending' => 
        array (size=0)
          empty
```

However the date is October 1, 2017, and since it's the 3rd today this record shouldn't be returned.

Appreciate your help btw.

**Comment by cklosowski** [comment]
@davidsherlock then you might need to use a different date format sending in.

**Comment by davidsherlock** [comment]
@cklosowski, thanks for your help - I got it working with the following code:

```
$start = date( 'Y-m-d', strtotime( $date_option ) );

	$year  = date( 'Y', strtotime( $start ));
	$month = date( 'm', strtotime( $start ));
	$day   = date( 'd', strtotime( $start ));

	$args = array(
		    'number' 		 	  => -1,
		    'status' 		 	  => 'clearance',
			'query_args'    	  => array(
				'date_query' 	  => array(
					'before'      => array(
						'year'    => $year,
						'month'   => $month,
						'day'     => $day,
					),
					'inclusive'   => true,
				)
			)
		);

		$commissions = eddc_get_commissions( $args );
```

One question however (apologies for being a pain here!), I created some meta data for each commission record using the following:

`$commission->update_meta( $meta_key, $meta_value );`

Since commission metadata is outside of the `WP_Query`, how would I query it using wp methods? I need it return a date range of keys (_edd_custom_deliverables_pending_date).

**Comment by sunnyratilal** [comment]
@davidsherlock you can query meta by creating a new instance of the `EDD_Commission` object.

E.g.
```php
$commission = new EDD_Commission( $object_id );
$value = $commission->get_meta( '_edd_all_access_info' );
```

**Comment by cklosowski** [comment]
@sunnyratilal he's wanting to do a meta query, so get commissions that contain a meta value.

I think we'll have to add this as a feature to the EDDC_DB system. I'll kick up an issue.

**Comment by davidsherlock** [comment]
@sunnyratilal, yeah I've used this already in my plugin! Works well. 

The bigger issue is querying the metadata via a metavalue for date ranges (in my case).

**Comment by cklosowski** [comment]
Ok issue created. #281 

for now, you'd just have to manually build a query out manually.
