### ISSUE TITLE
Feature Request: Additional Commission Rules/Classes

### ISSUE THREAD

**Issue by davidsanders** [easydigitaldownloads/EDD-Commissions#293]
I have a client that wants in addition to the commission fee, to charge the vendor a 'transaction fee of a few cents per item' sold. In our example, 50% + $0.30. This doesn't seem like it would be a difficult enhancement to hook up.. thoughts?

**Comment by davidsanders** [comment]
My client has also mentioned a per item fee, not specifically a transaction fee, in addition to the commission fee. Single transactions may contain downloads from multiple vendors, we'd deduct the per item fee from the commission.

**Comment by mintplugins** [comment]
I would advise doing this by hooking into the `eddc_commissions_calculated` filter and re-calculating them with the $0.30 subtracted from each commission so the the amounts generated reflect the fee you wish to charge Vendors. You are correct that doing this shouldn't be too difficult to do at all. 

We won't be adding this type of functionality to EDD Commissions right now though so I recommend doing it through custom development using that filter if you require this.

If you need more in-depth coding/development assistance we have a consultants page of EDD professionals available for hire here: https://easydigitaldownloads.com/consultants/

**Comment by davidsherlock** [comment]
@davidsanders, do you still need this? I could knock up a quick plugin for this as it's very similar to my commissions withholding tax snippet posted on the library.

**Comment by davidsanders** [comment]
I do yes, and that would be awesome!

**Comment by davidsherlock** [comment]
On the case @davidsanders! It's going to be a small commercial plugin (the price will be _very_ low - just to support future development and updates), but it should cover all instances of charging "fees" on commission amounts and you will be able to override on a per product and user basis.

For the sake of clarity, you want the following functionality:

- The ability to charge a "commission fee" on top of the recorded commission amount. I will make it possible to do this exclusively and inclusively. This will be a percentage (and not a flat fee) of the commission amount recorded (for example commission of £5 with 20% fee will be £6, and the £1 will be taken from the £5 leaving us with £4).

- The ability to set user specific fee rates that override the global fee settings.

- The ability to set product specific fee rates that will override the user and global fee settings.

Missing anything? I will add all the fees to the commissions table/commission view and reports to make it easy to figure out how much is owed/collected in fees.

**Comment by davidsherlock** [comment]
Do you need it to be taken from the original product (cart item) price or just the commission amount recorded? I am considering both as an option.

**Comment by davidsanders** [comment]
In our use case we offer two tiers to our users, regular and premium. As a
regular seller they are charged a flat fee of .50 per item per transaction.
Premium is .30. Our membership levels are determined by whether the user
has an active 'subscription' (recurring payment). We've already got the
integration between active recurring payments and commission rates
completed. We just need this last flat fee per item automated.

**Comment by davidsherlock** [comment]
So your sellers receive 50% of the item price, and this is already handled by commissions, but you want to add a flat (additional) fee of .50 (or .30 for premium users) to the commission amount (not the cart item price)? Just making sure I fully understand you.

**Comment by davidsherlock** [comment]
For simplification purposes - your seller receives £5 and is then charged a .50 "commission fee" leaving them with a £4.50 commission amount and the fee recorded as commission meta for reference.

**Comment by davidsanders** [comment]
Correct! I'm sure I can convince the owner to use it this way.

**Comment by davidsherlock** [comment]
Just a heads up @davidsanders that I have everything working and will be finalising the plugin tomorrow and releasing on Monday.

"Fees" can be set on a global, per user and per product basis. I'm adding some additional stuff in like fee reports and alike and we should be good to go. You can also view the "fee" on a per commission basis.

Here is a screenshot of the settings:

![screenshot 2017-11-12 02 10 06](https://user-images.githubusercontent.com/22668877/32695270-9eb63bde-c74e-11e7-8436-18f900e766b6.png)

**Comment by davidsherlock** [comment]
Just a quick update on this, I have completed the plugin, but need to draft up the marketing content for it so it can be launched as one of the first plugins on my new Sell Comet plugin site.

If you need the plugin urgently @davidsanders, drop me a message or reply here!

**Comment by davidsherlock** [comment]
@davidsanders, I have released the Commission Fees plugin through my new site: https://sellcomet.com/downloads/commission-fees/

Let me know if you have any questions and feel free to email me via the website contact form.
