### ISSUE TITLE
Add {sitename} to email template tags

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#294]
Downloads -> Settings -> Emails (tab) -> Commissions Notifications (section) ...

The {sitename} email tag should be available there.

**Comment by davidsherlock** [comment]
@SDavisMedia, PR submitted for this one: #307

**Comment by SDavisMedia** [comment]
Looking good to me! Works as expect. Thanks, @davidsherlock!
