### ISSUE TITLE
Date range discrepancy in reports vs exports

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#295]
When viewing the reports in Admin an October report DOES show all dates.
When generating the payout file, it is NOT including the last day of October and also NOT including last day on Commissions Export option under Reports > Export > Export Commissions (select 1 month).

**Comment by sunnyratilal** [comment]
**To replicate**
Create a new commission which is set to the last day of the month with a time of after `00:00:00` (e.g. `13:23:12`) then run a **detailed** commissions export for that month. You'll see the commission will be omitted.

**Comment by cklosowski** [comment]
working perfectly, merging.
