### ISSUE TITLE
Allow filtering of eddc_calc_commission_amount args

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#297]
I have written a plugin that calculates fees on commission records, however at the minute it only works on the actual commission amounts and allows percentage, flat rate, etc.  This is very useful for withholding taxes and offsetting payment processor fees.

In relation to WHT, In certain jurisdictions (specifically the United States), the withholding tax amount must be calculated and imposed on the base amount (i.e. the full item price including the commission markup), since my plugin only calculates on the commission _amount_ this wouldn't work well.

To fix this a filter is provided in the `eddc_calculate_payment_commissions` function, however this would mean repeating code in my plugin to loop through each of the commissions/recipients and re-calculate the amounts. A better method would be to add a filter to the $args just before the `eddc_calc_commission_amount` function is called. Here is what I propose:

```
$args = apply_filters( 'eddc_calc_commission_amount_args', array(
	'price'             => $price,
	'rate'              => $rate,
	'type'              => $type,
	'download_id'       => $download_id,
	'cart_item'         => $cart_item,
	'recipient'         => $recipient,
	'recipient_counter' => $recipient_counter,
	'payment_id'        => $payment->ID
) );
```
This would mean I could perform calculations on the price before the commission amount is calculated.

I will submit PR for this in a few minutes.

**Comment by davidsherlock** [comment]
PR submitted: #298

**Comment by pippinsplugins** [comment]
Looks good, merged!
