### ISSUE TITLE
Add action hooks to user meta table

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/EDD-Commissions#302]
I am building a lot of extensions at the minute for commissions and wanted a cleaner way of adding new user-specific options to the user meta without cluttering up the page.

Since my extensions are related to commissions, it makes sense to have some hooks at the start of and end of the table to allow new rows/cells to be easily added.

I suggest the following hooks (which I will submit PR for you): `eddc_user_meta_table_start` and `eddc_user_meta_table_end`.

**Comment by davidsherlock** [comment]
This is to avoid this issue:

![screenshot 2017-12-01 14 45 05](https://user-images.githubusercontent.com/22668877/33487865-a700d40e-d6a6-11e7-8ef3-11691856b6d9.png)

**Comment by davidsherlock** [comment]
PR submitted #303

**Comment by pippinsplugins** [comment]
@davidsherlock will get this out sometime next week probably.
