### ISSUE TITLE
Implement Field for FES inside of EDD Commissions

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#32]
Right now, FES has to manage and take care of adding the edd commissions field. This is really dumb, because if commissions wants to add an option, like adding the ability for vendors to use bank accounts, FES has to update instead of commissions. With the 2.3 release of FES, fields now use the fields API. This marks a great time for EDD Commissions to take care of managing its own field, like Simple Shipping does. I've gone ahead and nearly finished the code EDD Commissions will need to add, but basically its the field file and 4 lines to add the field to FES.

PR coming

**Comment by chriscct7** [comment]
Here's the starter that I wrote. You'll probably want to edit it a bit, like actually adding validation. We haven't nailed down how we'll do validation, so I'd probably leave that empty for now.

**Comment by pippinsplugins** [comment]
This is just for the payment email right?

**Comment by chriscct7** [comment]
Oops. This should have been closed out.
