### ISSUE TITLE
eddc_get_earned_commissions

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#43]
There should be a way to get all commissions earned by a vendor (basically like eddc_get_(un)paid_commissions but that gets the latest paid/unpaid commissions for a vendor). IT would be cool if we could get a little point release out that does this as it would prevent the need for FES to implement its own version of this for chriscct7/edd-fes/issues/646

**Comment by cklosowski** [comment]
What about `eddc_get_commissions()`. Working on converting the other functions for the specific statuses into a wrapper for this main one.

**Comment by cklosowski** [comment]
I need something like this for #44

**Comment by pippinsplugins** [comment]
I prefer `eddc_get_commissions()`. That way we have one function that accepts a variety of paremters.

**Comment by cklosowski** [comment]
yes, and I'm mkaing it so you can pass in either a string for a status, or an array of statuses so you can pull mutliples if needed.

**Comment by cklosowski** [comment]
will have it in #44

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Make sure it supports getting commissions for specific users too.

On Fri, Jul 3, 2015 at 1:54 PM, Pippin Williamson <pippin@pippinsplugins.com

**Comment by cklosowski** [comment]
yeah, it litterly just passes through.

**Comment by pippinsplugins** [comment]
:+1:
