### ISSUE TITLE
Add Commissions tab to Customer view if customer has commissions.

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#45]

**Comment by cklosowski** [comment]
![image](https://cloud.githubusercontent.com/assets/1390124/8447005/d2324a76-1f66-11e5-86f6-ba3242461e5d.png)

**Comment by pippinsplugins** [comment]
`# Paid Sales` doesn't read right to me. Could it be combined to read like `$14.50 unpaid commissions via 4 sales`?

**Comment by cklosowski** [comment]
![screen shot 2015-07-07 at 10 06 13 am](https://cloud.githubusercontent.com/assets/1390124/8552116/dbe7ee58-248f-11e5-8bcd-3b71bf234507.png)
![screen shot 2015-07-07 at 10 05 30 am](https://cloud.githubusercontent.com/assets/1390124/8552117/dbe83412-248f-11e5-82e3-fafff94d4983.png)

It looked really odd with `via 0 sales`, so now it only shows the sales count and the link when there are sales in that status

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Looks great to me

**Comment by pippinsplugins** [comment]
`Payments` should be `Commissions`: https://cloudup.com/cBmoS8Dt550
