### ISSUE TITLE
Add search to commissions

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#5]
Search by payment ID, recipient, and possibly amount.

**Comment by pippinsplugins** [comment]
I don't think we need to support searching by payment ID (we can filter by payment ID already and can find commissions for a payment from View Order Details screen). I do, however, think we should support searching by email address, both the paypal email and the user email.

**Comment by cklosowski** [comment]
This will require that https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3595 be completed and in core.
