### ISSUE TITLE
Better vendor reports

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#7]
- [x] List products vendor receives commissions for and include sale count / earnings `[edd_commissioned_products]`
- [x] Show a Commissions Overview table `[edd_commissions_overview]`
- [x] Show a graph, filterable by date `[edd_commissions_graph]`

**Comment by cklosowski** [comment]
@pippinsplugins Are you thinking a single overall filter? or one for each section of the shortcode section?

**Comment by pippinsplugins** [comment]
@cklosowski Either a separate section or a separate short code.

**Comment by pippinsplugins** [comment]
@chriscct7 pinging you for inclusion of graphs / overview in FES vendor pages.

**Comment by chriscct7** [comment]
@pippinsplugins ?

**Comment by pippinsplugins** [comment]
[edd_commissions_graph] and [edd_commissions_overview]
