### ISSUE TITLE
Amounts sent to PayPal incorrect with multiple vendors and shipping

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#75]
As raised in [this ticket](https://secure.helpscout.net/conversation/107602166/13555/), it appears there is an issue with the payment amounts sent to PayPal when using PayPal Adaptive Payments and an order is placed that includes items from multiple vendors and shipping fees (simple shipping).

The amounts recorded in Downloads > Commissions are correct but the actual amounts in PayPal are wrong.

**Comment by pippinsplugins** [comment]
Looks like this is due to shipping rates and tax options not being taken into account.

**Comment by pippinsplugins** [comment]
I think ^ will fix it. I'm going to ask the customer that noticed it to beta test to confirm.

**Comment by SDavisMedia** [comment]
Any word form the customer?

**Comment by pippinsplugins** [comment]
Negative.

**Comment by SDavisMedia** [comment]
@pippinsplugins Any way we can take over testing on this? I don't have PAP at the moment. Are you able to test it?

**Comment by pippinsplugins** [comment]
@SDavisMedia You can test without a PayPal app. Just uncomment this line and then verify amounts are correct after submitting checkout: https://github.com/easydigitaldownloads/EDD-Commissions/blob/ae4ea3ab81c5ac9bd260ad1c874d8545f4ccf884/includes/adaptive-payments.php#L135

**Comment by pippinsplugins** [comment]
@SDavisMedia I just had a user confirm that this fixed the issue.

**Comment by pippinsplugins** [comment]
@cklosowski Could you give this a look over?
