### ISSUE TITLE
Dates are incorrectly parsed for first and last day of the month when exporting

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#78]
If you export May 1 to May 31st, you actually only get May 2nd to May 30th.

**Comment by ghost1227** [comment]
@sunnyratilal and I have been testing this tonight, and neither of us has been able to reproduce this issue.

**Comment by sunnyratilal** [comment]
@pippinsplugins Can't replicate this - correct data is being generated.

**Comment by ghost1227** [comment]
Given this is a two year old bug, when's the last time anyone reported it (or we saw it on the EDD site)?

**Comment by pippinsplugins** [comment]
Let's close as invalid.
