### ISSUE TITLE
Batch export file fails to download

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/EDD-Commissions#79]
On some sites (particularly Pagely it seems), the batch export file fails to download.

**Comment by pippinsplugins** [comment]
I just had this happen on the live EDD site.

**Comment by pippinsplugins** [comment]
![screen shot 2015-08-14 at 9 11 26 am](https://cloud.githubusercontent.com/assets/1034109/9275691/78793dfc-4264-11e5-9384-123479181acd.png)

**Comment by pippinsplugins** [comment]
This still happens on the live EDD site for unknown reasons.

**Comment by ghost1227** [comment]
@pippinsplugins Not sure if it's the same issue or not, but my last few attempts to export have resulted in an endless spinner and no export. Doesn't actually throw that error for me, just never successfully exports.

**Comment by pippinsplugins** [comment]
@ghost1227 ok try and track it down please.

**Comment by pippinsplugins** [comment]
I haven't seen this happen in a while on our sites.

@ghost1227 do your exports still spin endlessly?

**Comment by ghost1227** [comment]
@easydigitaldownloads/core-devs I'm struggling to consistently reproduce either form of this issue (the message @pippinsplugins is seeing, or the endless spinner i've been seeing). Anyone with a few moments, please chime in on thoughts, etc. (Especially @cklosowski)

**Comment by mintplugins** [comment]
Possibly related:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5465

**Comment by ghost1227** [comment]
@pippinsplugins Is it possible that your failures are related to the priority bug @mintplugins found? I can't find any other viable reason for this to be happening.

**Comment by pippinsplugins** [comment]
Possibly but impossible to say. I haven't had a failure in a while. Will do
an export tomorrow and see if it fails. If it works, we can close as fixed.

**Comment by pippinsplugins** [comment]
This worked fine, closing as fixed.
