### ISSUE TITLE
Back Pagination Links Don't Work on Unpaid Commissions

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#83]
On page 7, this is the link for page 6:
https://easydigitaldownloads.com/your-account/&eddcup=6?eddcup=7

Could affect paid and other pagination links as well

**Comment by ghost1227** [comment]
I can't replicate this either locally or on the EDD site, @pippinsplugins have you actually seen this?

**Comment by ghost1227** [comment]
Since this can't be reproduced (at least anymore) I'm closing as invalid

**Comment by cklosowski** [comment]
going to actually close it this time :)
