### ISSUE TITLE
Commissions Shows For All Sales

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/EDD-Commissions#84]
When I use [edd_commissions_graph] I see the entire total sales + earnings for all of the store when I only have 2 sales assigned to the user ID.

**Comment by pippinsplugins** [comment]
@christ0ph3r Are you logged in when viewing the page?

**Comment by christ0ph3r** [comment]
Yes.  I just tested on a new server + fresh installs + 2015 theme.

The shortcode I am using is [edd_commissions_graph] .

Please note all the other shortcodes return the correct values.

It actually doesn't show the entire sales like I originally commented.  It shows the entire commissions which is still just as bad.

For example say your store has 3 $3 sales.  1 sale has no commissions.  Joe gets 1 comission and steve gets the last comission.

Now Joe and Steve will see $6 in earnings and 2 sales in their chart when they are suppose to see $3 in earnings and 1 sale.

I have tried with multiple user roles and get the same results.

**Comment by christ0ph3r** [comment]
Hey @pippinsplugins I have tested on 3 different hosts, multiple datasets, and multiple user roles.  I am still getting the issue.  Can you confirm?

**Comment by christ0ph3r** [comment]
Hey @pippinsplugins sorry to bump again just not sure if you saw this.  

I would really like to use this graph shortcode.  It is such a cool feature. But it does not work correctly from everything I have seen and I have spent many hours testing this to make it work.  I have tried on many hosts with fresh installs.

**Comment by pippinsplugins** [comment]
Sorry, I haven't had a chance to look at this yet. I'll look soon.

**Comment by pippinsplugins** [comment]
@christ0ph3r Tracked it down. We'll push out an update today to fix it.

**Comment by christ0ph3r** [comment]
Nice find.  Thanks so much!  Will try it out this weekend.
