### ISSUE TITLE
Infinite Exporting

### ISSUE THREAD

**Issue by christ0ph3r** [easydigitaldownloads/EDD-Commissions#85]
If you attempt to generate a file with a higher amount then what is owed it seems to glitch and doesn't have a check for that.

For example I have 2 $3 test commissions and put 80 as the minimum number.  The blue bar loads over and over + never stops.

Seems it would crash the site eventually depending on the server specs.

**Comment by pippinsplugins** [comment]
This does not happen to me. @christ0ph3r Are you still seeing it?

**Comment by christ0ph3r** [comment]
I updated and tested.  I now get "No data found for export parameters".  The issue doesn't seem to exist anymore.

:+1:
