### ISSUE TITLE
Bundled Cert Update

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#86]
PayPal is requiring IPN requires that have a bundled cert to use a new certificate here:
https://knowledge.symantec.com/support/mpki-for-ssl-support/index?page=content&actp=CROSSLINK&id=SO5624

The bundled masspay uses one, and we need to swap it out and push out an update ASAP as PayPal will stop honoring the certificate at any time between right now and September 30th

Info:
https://devblog.paypal.com/paypal-ssl-certificate-changes/

Timeline:
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1766&viewlocale=en_US&direct=en

**Comment by cklosowski** [comment]
Looks like this most urgent one is for services calling the `www.paypal.com` endpoint. This is slated for Sandbox in Q1 2016 and Live Q2 2016.

@pippinsplugins Can you check me on those links above and make sure i'm reading that right?

**Comment by chriscct7** [comment]
Chris K is correct. No update is required. We should slate this for a later release when SHA 256 is more widely available. Agree with the milestone change.

**Comment by chriscct7** [comment]
See related #87 for a more time sensitive update though

**Comment by pippinsplugins** [comment]
We don't actually use the masspay API in Commissions. The library files are there from when we were thinking of introducing scheduled commissions and such.

We need to just remove all of the PayPal library files and this will be done.

Need to investigate PayPal Adaptive Payments to see if it needs updated though.

**Comment by pippinsplugins** [comment]
PayPal Adaptive Payments doesn't include any certificates so we're good there too. Closing as invalid :) whew

**Comment by chriscct7** [comment]
Braintree is a PayPal product. If we still support that extension, we probably have to update that cert as well
