### ISSUE TITLE
Update SHA1 Cert

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/EDD-Commissions#87]
While investigating for #86, @chriscct7 and I noticed that the current SHA1 cert for the endpoint we're using is going to expire:
Renewal Schedule (SHA-1) by Endpoint
Certificates are used to verify the identity of a person or device, authenticate a service, or encrypt files. Occasionally, these certificates require renewal. Please review the schedule below and make sure you are ready for such events by consulting with your technology team or the individual(s) responsible for your PayPal integration.

![screen shot 2015-09-10 at 4 35 23 pm](https://cloud.githubusercontent.com/assets/1390124/9803694/fd72f98c-57d9-11e5-8ace-9acef3b635c8.png)

We need to find a way to get this cert and update it.

**Comment by cklosowski** [comment]
@pippinsplugins do know where to grab these things? I cna't find them anywhere.

**Comment by chriscct7** [comment]
+1

Maybe call PayPal directly, but this update needs to be into customers WP installs before they expire, so time is of the essence

**Comment by pippinsplugins** [comment]
See #86
