### ISSUE TITLE
Tiered commission rates

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/EDD-Commissions#89]
It would be interesting to see an option that changes the global commissions for authors based on the level of sales they have. Example:
Sales Total       Commission Percentage
0 - 1000            10%
1000- 10000     20%
10000 - unlimited 30%

**Comment by carter2422** [comment]
This would be great.

On Friday, September 25, 2015, Chris Christoff <notifications@github.com>
wrote:

> It would be interesting to see an option that changes the global
> commissions for authors based on the level of sales they have. Example:
> Sales Total Commission Percentage
> 0 - 1000 10%
> 1000- 10000 20%
> 10000 - unlimited 30%
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/EDD-Commissions/issues/89>.
>


-- 
Jonathan Williamson
http://cgcookie.com

**Comment by pippinsplugins** [comment]
Tiered commission rates. :+1:

**Comment by mindctrl** [comment]
Good idea. Related, we've had several requests for varying commission rates based on a status of some kind (membership, purchasing a particular item, whatever). Could get tricky really quickly. Sales seems like a good obvious one to start with, but if we abstract it, we may be able to integrate other things with it.

**Comment by rahilwazir** [comment]
Would love to have this, my client is also requesting this feature. Any ETA when it should be ported :smile: ?

**Comment by davidsherlock** [comment]
I built this as a commercial plugin: sellcomet.com/downloads/tiered-commission-rates/

This issue can be closed.
