### ISSUE TITLE
Improve payout generation experience when no dates are specified

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Commissions#92]
When generating a payout file, if you specify no date range an empty file gets generated and downloaded. I think it would be better to show some kind of notice instead.

Customer reported [here](https://secure.helpscout.net/conversation/133856529/19905/).

**Comment by cklosowski** [comment]
@mindctrl would love your feeback on this approach, ties into the core's `is_empty` status and gives us a report that nothing was returned due to the ranges specified.

**Comment by mindctrl** [comment]
@cklosowski this looks much nicer than getting an empty file!

![image](https://cloud.githubusercontent.com/assets/1254870/13057214/b38920d6-d3e8-11e5-99d0-ba1265feba54.png)

Thoughts on adding the word `amount` after `minimum` in the notice? I know it matches the text field above, but I'd rather they both have amount really, just for the sake of clarity.

**Comment by cklosowski** [comment]
@mindctrl Sure, that notice was added in #114. I'll get it updated here for clarity.

**Comment by mindctrl** [comment]
@cklosowski :+1: looks good
