### ISSUE TITLE
Update customer UI tab for EDD changes

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#95]
The Commission tab in the Customer UI will lose its formatting when EDD issue/3820 is implemented: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3820

![1dbd872e-61e5-11e5-9d4d-b334f2e5889c](https://cloud.githubusercontent.com/assets/2359131/10901411/9d1ea9ee-81a2-11e5-8ead-1f62f3a57819.png)

**Comment by SDavisMedia** [comment]
When EDD issue/3820 is live, this will display as expected.

![screen shot 2015-11-02 at 8 44 13 pm](https://cloud.githubusercontent.com/assets/2359131/10901402/872a44e0-81a2-11e5-947e-249d91e477be.png)

**Comment by pippinsplugins** [comment]
This works properly with EDD 2.5 but breaks again with any version prior, so let's wait to release this update until 2.5 is out.

**Comment by cklosowski** [comment]
Closing, this will go with 3.2.5 today
