### ISSUE TITLE
allow Simple Shipping to honor Calculation Base setting

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Commissions#97]
As of now, the shipping fee applied by simple shipping is added to the price of the cart items and the commissions are calculated based on that total. Commissions has a setting for this, Calculation Base. It honors taxes and discounts but ignores shipping fees.

Because of this, if you view the shipping fee from a similar standpoint as taxes and discounts, this essentially means that the Calculation Base setting of Subtotal is **not** relevant for shipping. I think it should be. And if it is, it introduces a new issue:

If the shipping fee is treated like taxes or discounts, that means the site owner can elect to have the commission Calculation Base set to Subtotal and the commissions will be calculated based on the price of the actual product(s). But there, the additional amount for shipping has to go somewhere. The vendor or the site owner? With that, the new logic could be:

```php
if ( 'subtotal' == $calculation_base ) {
	if ( 'vendor' == $who_ships_it ) { // new setting
		// give shipping fee to the vendor
	} else {
		// give shipping fee to site owner
	}
} else {
	// everything stays exactly as it is now
}
```

**Comment by pippinsplugins** [comment]
![screen shot 2015-11-23 at 9 48 09 am](https://cloud.githubusercontent.com/assets/1034109/11341271/6421bfe8-91c7-11e5-8c43-fb48a2d3ca2c.png)
![screen shot 2015-11-23 at 9 48 19 am](https://cloud.githubusercontent.com/assets/1034109/11341270/6420d75e-91c7-11e5-98f4-7a9f00b68384.png)
